### ISSUE TITLE
Constant Stale

### ISSUE THREAD

**Issue by ebarretopr** [hassio-addons/addon-nut#100]
# Problem

I have a cyberpower and APC ups connected to a Home Assistant Blue unit. I am using usbhid-ups driver for both, the APC one works without a problem but the Cyberpower Model CP1500 AVR works for a while then it becomes stale, I have to restart the Add-on and it works again for a while and repeats the issue.

**Comment by sinclairpaul** [comment]
Please have a look at #91

**Comment by ebarretopr** [comment]
Thanks, I will take a look

**Comment by mamos76** [comment]
even updating to the latest version the problem was not solved. I added "upsmon deadtime" in the configuration but the problem persists

**Comment by sinclairpaul** [comment]
Please post your config and logs

**Comment by mamos76** [comment]
> Please post your config and logs
users:
  - username: mamos76
    password: oscar@303nutserver
    instcmds:
      - all
    actions: []
devices:
  - name: CyberPower_1500
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'
upsd_maxage: 25
pollinterval: 15
upsmon_deadtime: 25

**Comment by mamos76** [comment]
users:
  - username: xxxxxx
    password: xxxxxx
    instcmds:
      - all
    actions: []
devices:
  - name: CyberPower_1500
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'
upsd_maxage: 25
pollinterval: 15
upsmon_deadtime: 25

**Comment by mamos76** [comment]
6670.440902	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6675.441982	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6680.442363	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6685.442549	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6690.442873	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6695.443213	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6700.443513	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6705.443803	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6710.444096	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6715.444339	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6720.444579	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6725.444941	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6730.445192	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6735.445442	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6740.445693	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6745.445975	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6750.446267	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6755.446541	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6760.446797	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6765.447040	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6770.447280	Poll UPS [CyberPower_1500@localhost] failed - Data stale
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
6775.447622	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6780.447853	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6784.457608	Send ping to UPS [CyberPower_1500] failed: Resource temporarily unavailable
6785.453724	Connected to UPS [CyberPower_1500]: usbhid-ups-CyberPower_1500
6785.448241	Poll UPS [CyberPower_1500@localhost] failed - Driver not connected
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
6812.457634	Data for UPS [CyberPower_1500] is stale - check driver
6815.450101	Poll UPS [CyberPower_1500@localhost] failed - Data stale
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
6820.450696	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6825.450942	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6830.451182	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6835.451499	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6840.451914	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6845.452163	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6850.452450	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6855.452700	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6860.453137	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6865.453435	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6870.453776	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6875.454046	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6880.454284	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6885.454654	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6890.455032	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6895.455357	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6900.455846	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6905.456172	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6910.457036	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6915.457529	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6920.457975	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6925.458227	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6930.458806	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6935.459281	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6940.459787	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6945.460131	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6950.460537	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6955.460934	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6960.461277	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6965.461552	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6970.461844	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6975.462096	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6980.462545	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6985.462850	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6990.463156	Poll UPS [CyberPower_1500@localhost] failed - Data stale
6995.463456	Poll UPS [CyberPower_1500@localhost] failed - Data stale
7000.463737	Poll UPS [CyberPower_1500@localhost] failed - Data stale
7005.464061	Poll UPS [CyberPower_1500@localhost] failed - Data stale
7010.464299	Poll UPS [CyberPower_1500@localhost] failed - Data stale
7015.464514	Poll UPS [CyberPower_1500@localhost] failed - Data stale
7020.464843	Poll UPS [CyberPower_1500@localhost] failed - Data stale
7025.465203	Poll UPS [CyberPower_1500@localhost] failed - Data stale
7030.465422	Poll UPS [CyberPower_1500@localhost] failed - Data stale
7035.465709	Poll UPS [CyberPower_1500@localhost] failed - Data stale

**Comment by sinclairpaul** [comment]
I gave an example config at https://github.com/hassio-addons/addon-nut/issues/91#issuecomment-778357271

Please try that.

**Comment by ebarretopr** [comment]
Hi, 

This is my config, 23 hours later no stale

users:
  - username: xxxxxxx
    password: xxxxxxx
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 0764*
      - pollinterval = 15
  - name: apcups
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 051d*
mode: netserver
shutdown_host: 'false'
list_usb_devices: 'true'
upsd_maxage: 25
upsmon_deadtime: 25
