### ISSUE TITLE
Need option to set the 'listen' in UPSD.CONF to gateway IP Synology NAS to see nut.

### ISSUE THREAD

**Issue by QuickSwitchLK** [hassio-addons/addon-nut#102]
As with last changes could you please add the ability to set extra listen ip's in UPSD.CONF. If I edit the file in the container the data is lost when nut is restarted so it cant load on start up the listen ip.

**Comment by sinclairpaul** [comment]
I'm not sure of the need to do this in a standard setup, it's configured to listen internally in the container, which runs on an isolated network.

The challenge is how complex the addon configuration becomes, if you need this level of config, you probably would be better running NUT elsewhere.
