### ISSUE TITLE
NUC usbhid-ups problem

### ISSUE THREAD

**Issue by Sergi-CP** [hassio-addons/addon-nut#124]
# Problem/Motivation

> After last core update i can't start the addon. I can't put the log because freezes my NUC, I've the STARTUP option disabled, then the only thing that i can do is restart my PC. I see, changin the driver that the log file (log_level: trace) arrives to driver init, then if I put the usbhid-ups the addon arrives to init and then freezes the NUC.

**Comment by sinclairpaul** [comment]
There isn't any information here for anyone to help, and as this doesn't appear to be caused by any changes in the addon, I doubt it is at all related to the addon itself.

**Comment by Sergi-CP** [comment]
Hi, after last core update all works agin... incredible. Thanks.
