### ISSUE TITLE
fopen /var/run/nut/upsd.pid: No such file or directory

### ISSUE THREAD

**Issue by kmelihk** [hassio-addons/addon-nut#131]
# Problem/Motivation
Hello, I'm unable to get this addon to a functional state in netserver & client mode with a Cyberpower UPS directly plugged into USB port. I'm running the official pi image with containers on Raspberry Pi 4.

## Expected behavior
I expected to be able to follow instructions provided on github page (Configuring as netserver on addon configuration tab, and adding a sensor through configuration.yaml

## Actual behavior
If I add a sensor through configuration.yaml, I get the error message below in my log shown on core log:

`[homeassistant.components.sensor] The nut platform for the sensor integration does not support platform setup. Please remove it from your config.`

and message below on supervisor log:

`
21-05-12 17:00:01 WARNING (MainThread) [supervisor.addons.options] Unknown option 'resources' for Network UPS Tools (a0d7b954_nut)
`

One oddity I can see in my logs is the title of my issue. Full output is below:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.5.1
 Home Assistant Supervisor: 2021.04.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[22:47:24] INFO: Setting mode to netserver...
[22:47:24] INFO: Connected USB devices:
Bus 002 Device 002: ID 0bda:9210 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0764:0601 Cyber Power System, Inc. PR1500LCDRT2U UPS
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[22:47:25] INFO: Generating /etc/nut/upsd.users...
[22:47:25] INFO: Configuring user: melih
[22:47:25] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[22:47:25] INFO: Configuring Device named Cyberpower_UPS...
[22:47:25] INFO: Starting the UPS drivers...
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Using subdriver: CyberPower HID 0.4
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:47:26] INFO: Starting the UPS information server...
   0.000000	fopen /var/run/nut/upsd.pid: No such file or directory
   0.001567	listening on 0.0.0.0 port 3493
   0.002256	Connected to UPS [Cyberpower_UPS]: usbhid-ups-Cyberpower_UPS
[22:47:26] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.001164	Using power down flag file /etc/killpower
   0.001770	UPS: Cyberpower_UPS@localhost (master) (power value 1)
   0.002290	debug level is '1'
   0.002619	Warning: running as one big root process by request (upsmon -p)
   0.003776	Init SSL without certificate database
   0.021400	Trying to connect to UPS [Cyberpower_UPS@localhost]
   0.553051	User upsmonmaster@127.0.0.1 logged into UPS [Cyberpower_UPS]
   0.024868	Logged into UPS Cyberpower_UPS@localhost
  27.220571	Data for UPS [Cyberpower_UPS] is stale - check driver
  27.220799	UPS [Cyberpower_UPS] data is no longer stale
```

And below is my configuration:

```
users:
  - username: *****
    password: *****
    instcmds:
      - all
    actions: []
devices:
  - name: Cyberpower_UPS
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 0764
    resources:
      - ups.load
      - input.voltage
mode: netserver
shutdown_host: 'false'
list_usb_devices: 'true'
```

I do not necessarily know if resources section and list_usb_devices is necessary but I was experimenting with different settings to get this functional.

If I try to run upsd directly through portainer console I also get the fopen error related to upsd.pid, however I'm able to use upsc.

`
root@a0d7b954-nut:/# upsc Cyberpower_UPS@127.0.0.1
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 20
battery.mfr.date: CPS
battery.runtime: 7025
battery.runtime.low: 300
battery.type: PbAcid
battery.voltage: 27.4
battery.voltage.nominal: 24
device.mfr: CPS
device.model: GX1500U
device.serial: QA9KX2000643
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.parameter.vendorid: 0764
driver.version: 2.7.4
driver.version.data: CyberPower HID 0.4
driver.version.internal: 0.41
input.voltage: 124.0
input.voltage.nominal: 120
output.voltage: 140.0
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.delay.start: 30
ups.load: 4
ups.mfr: CPS
ups.model: GX1500U
ups.productid: 0601
ups.realpower.nominal: 900
ups.serial: QA9KX2000643
ups.status: OL
ups.test.result: No test initiated
ups.timer.shutdown: -60
ups.timer.start: -60
ups.vendorid: 0764
`

I appreciate if you can provide some assistance.

**Comment by sinclairpaul** [comment]
From the logs you shared, the addon is running correctly.  The error you shared is that the integration in HA failed to setup, as it is required to be performed from the GUI.  Further details are on the integration page https://www.home-assistant.io/integrations/nut/

The addon provides the software (in this case NUT), HA provides the Integration with Home Assistant itself.

Resources isn't a valid addon configuration option.

I would also suggest using the following based on previous issues logged with Cyberpower devices.
```
devices:
  - name: Cyberpower
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 15
mode: netserver
shutdown_host: 'false'
upsd_maxage: 25
upsmon_deadtime: 25
```

**Comment by kmelihk** [comment]
Thank you very much Paul, I was able to get it working by manually adding the integration. I was confused with adding the addon vs adding the integration. Once I added the integration, my UPS showed up. I appreciate quick and professional response.
