### ISSUE TITLE
Can't connect the upsd by remote NUT clients

### ISSUE THREAD

**Issue by erkr** [hassio-addons/addon-nut#143]
# Problem/Motivation

I have my UPS connected via USB to the Raspberry Pi hosting Home assistant with this add-on.
From both my NAS and PC I would like to connect NUT as remote NUT clients. That doesn't work. It look like the remote access is not enabled. With UPSC on these machines I can't connect either:
root@NAS> upsc mge@192.168.178.47:3493
Error: Connection failure: Connection refused
In the configuration settings the network se4ction should allow to define a host. (I presume to enable remote clients), BUT that name doesn't persist! After restarting NUT and leaving and reentering the menu, the settings is undefined again:
>Container	Host	Omschrijving
3493/tcp	     Uitgeschakeld    Network UPS Tools

the logfile mentions:
>[21:22:47] INFO: Starting the UPS information server...
   0.000000	fopen /var/run/nut/upsd.pid: No such file or directory
   0.019735	listening on 0.0.0.0 port 3493

best regards
Eric

**Comment by sinclairpaul** [comment]
Did you do this on the config page:

![image](https://user-images.githubusercontent.com/24625998/120701362-bd8e2700-c480-11eb-9091-8dabd68b0ded.png)

**Comment by erkr** [comment]
Thanks, didn't get that, Thougt I had to specify a host name. Remote UPSC works now !!!

**Comment by sinclairpaul** [comment]
Glad you got it working.  Will close this out.
