### ISSUE TITLE
User defined command/part of SHUTDOWNCMD or custom shutdown script

### ISSUE THREAD

**Issue by myhomeiot** [hassio-addons/addon-nut#144]
In order to manage UPS shutdown and other things before host shutdown request, please add possibility to add into configuration the commands which executes before shutdownhost script or possibility to specify path to user script which executes instead shutdownhost script.

Thanks in advance.

https://github.com/hassio-addons/addon-nut/pull/36#issuecomment-782755536
#35

**Comment by sinclairpaul** [comment]
Thanks, but you are linking to closed issues, with a reason why it wasn't implemented previously.

**Comment by myhomeiot** [comment]
Sorry, I was thinking that "**However that would be a longterm goal.**" means something possible.

Unfortunatelly without possibility even for advanced user to specify command of UPS shutdown, plugin mode 'netserver' is useless. :-(
