### ISSUE TITLE
Unable to detect more than one UPS

### ISSUE THREAD

**Issue by GothShoot** [hassio-addons/addon-nut#146]
# Problem/Motivation

> Unable to use more than one UPS

## Expected behavior

> UPS are correctly handled by driver and nut can display the ups's

## Actual behavior

> Ressource busy when try to access the second UPS

## Steps to reproduce

> Try to detect 2 or more UPS (i use Odroid N2)

## Proposed changes

> Probably a problem with the driver usb-generic UPS

**Comment by sinclairpaul** [comment]
There are also examples in the documentation which shows how to configure multiple devices, you won't be able to leave them both on auto only.

https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#sub-option-config

**Comment by GothShoot** [comment]
Last HA release seem to resolve problem 🤔

**Comment by sinclairpaul** [comment]
The HA release itself has no implication for the addon.

However as it seems you have it resolved, and there are no logs/config, I will close this out.
