### ISSUE TITLE
Limited Input Voltage reading

### ISSUE THREAD

**Issue by facuzestoa** [hassio-addons/addon-nut#153]
# Problem/Motivation

Nut is not reporting correct Input Voltage from UPS

## Expected behavior

Have Input Voltage reading from 0 (no voltage) up to maximum range 

## Actual behavior

UPS is Back-UPS XS 1100CI by American Power Conversion connected via USB to Raspberry Pi 4 with Home Assistant 2021.7.1
The input voltage reading is limited between 128 Vca to 230 Vca, this never happened before when I was using apcupsd with same UPS. Indeed I have one automation in node-red that detects when Voltage is over 232 Vca and send me a message to my mobile (my electricity provider is not reliable at all, could have more that 240Vca in the lines), and also some automation at 0 (cero) to shutdown other equipment.
Entities
Apc Battery Charge = 100 %
Apc Battery Date = 2001/09/25
Apc Battery Manuf. Date = 2018/05/16
Apc Battery Runtime = 12,800 s
Apc Battery Voltage = 27.1 V
Apc Input Voltage = 230.0 V
Apc Load = 3 %
Apc Status = Online
Apc Status Data = OL

Log
[18:05:38] INFO: Starting the UPS drivers...
   0.000000	Starting UPS: apc
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Using subdriver: APC HID 0.96
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:05:39] INFO: Starting the UPS information server...
   0.000000	fopen /var/run/nut/upsd.pid: No such file or directory
   0.002204	listening on 0.0.0.0 port 3493
   0.004959	Connected to UPS [apc]: usbhid-ups-apc
[18:05:39] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000643	Using power down flag file /etc/killpower
   0.001007	UPS: apc@localhost (master) (power value 1)
   0.001354	debug level is '1'
   0.001413	Warning: running as one big root process by request (upsmon -p)
   0.002199	Init SSL without certificate database
   0.008053	Trying to connect to UPS [apc@localhost]
   0.552521	User upsmonmaster@127.0.0.1 logged into UPS [apc]
   0.012406	Logged into UPS apc@localhost

## Steps to reproduce

Here is my config:

users:
  - username: nutmag
    password: mypaswd
    instcmds:
      - all
    actions: []
devices:
  - name: apc
    driver: usbhid-ups
    port: auto
    config:
      - desc = "APC UPS"
      - vendorid = 051d
      - pollfreq = 10
      - maxreport
mode: netserver
shutdown_host: 'false'
log_level: debug

## Proposed changes

Tried several configurations and restarted HA and UPS several times

**Comment by sinclairpaul** [comment]
The application is installed using the packages distributed on Debian.  You would  need to log the issue with the NUT application itself.

I would also recommend checking that your model is on the compatibility list https://networkupstools.org/stable-hcl.html

**Comment by facuzestoa** [comment]
BACK-UPS XS LCD  USB is listed and compatible with usbhid-ups driver.
How to log the ssue with the NUT application itself ?
Thanks in advance!
