### ISSUE TITLE
Scan Interval not working.

### ISSUE THREAD

**Issue by pmd5700** [hassio-addons/addon-nut#156]
# Problem/Motivation

> Scan Interval not working properly.

## Expected behavior

> I have the Scan Interval set at 30 seconds (I have also tried 60 seconds), but my sensors appear to update about every 5 minutes.

## Actual behavior

> Scan Interval updates longer than expected.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
I believe you are referring to the HA integration, not the addon, so your issue would need to be raised with the HA project (or I would suggest seeking help on the forums or Discord first).

**Comment by pmd5700** [comment]
Sorry, you're right.
