### ISSUE TITLE
Is there a possibility to set the NUT-server name?

### ISSUE THREAD

**Issue by carsten-h** [hassio-addons/addon-nut#16]
Hello!

I want to use the Pi with an attached UPS as a NUT-server (netserver mode).
One of the netclients will be my QNAP NAS. But QNAP is expecting that the name of the netserver (not the hostname!) is "qnapups".  But I see no possibility to set the name of the netserver when using this addon.
When running in netclient mode I can set remote_ups_name but I can not set "local_ups_name" in netserver mode.

Or am I don't seeing the correct configuration option.

**Comment by sinclairpaul** [comment]
The name I believe you are referring to (from some google help), is the name configured by the config item devices.name.

**Comment by carsten-h** [comment]
You mean if I am using this configuration:

```
  "devices": [
    {
      "name": "qnapups",
      "driver": "usbhid-ups",
      "port": "auto",
      "config": []
    }
```

it should work? This is really easy. Thank you very much!

Then this issue can be closed!
