### ISSUE TITLE
New warning in log 

### ISSUE THREAD

**Issue by lukexperias** [hassio-addons/addon-nut#161]
Hi, I have this warning in Home Assistant addon (Hassos on raspberry 4):

[supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Network UPS Tools
21-07-29 19:35:00 WARNING (MainThread)

[supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Network UPS Tools

**Comment by sinclairpaul** [comment]
Please post the full addon startup log, are you running a fork from somewhere?

**Comment by lukexperias** [comment]
![Screenshot_2021-07-29-22-06-36-31](https://user-images.githubusercontent.com/46723176/127558858-13521168-15ce-4238-b9ce-9059ccd013eb.jpg)

What do you mean with fork?

**Comment by sinclairpaul** [comment]
I mean that it isn't this addon causing the errors to be logged.  Please goto the Supervisor Tab, Addon Store, and click the three dots at the top right.  What do you have listed under repositories?

It is likely you have reference to another NUT addon, which is generating the warnings.

**Comment by lukexperias** [comment]
![Screenshot_2021-07-29-22-43-25-54_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/46723176/127563240-104dc751-dca7-4ca0-9f66-18431623616f.jpg)


This is what I see there... THANKS A LOT

**Comment by lukexperias** [comment]
![Screenshot_2021-07-29-22-51-14-26](https://user-images.githubusercontent.com/46723176/127564104-b52ea30d-9aca-47de-8703-9bcee6f8bafe.jpg)

**Comment by sinclairpaul** [comment]
The one that is causing your warnings is <https://github.com/jumping2000/hassio-addons>

Either report the error there, or remove it if you are not using that addon.

**Comment by lukexperias** [comment]
Thanks a lot, I'm trying like this.
