### ISSUE TITLE
Cleanup netclient mode configuration

### ISSUE THREAD

**Issue by gb53smith** [hassio-addons/addon-nut#164]
# Problem/Motivation

> Failed to save configuration without optional users: and devices: sections when mode: netclient

## Expected behavior

> When mode is netclient I just want to connect to a remote netserver using the remote_ups* options.

## Actual behavior

> Fails to save.  Expecting users: and devices: options .  These options are only applicable for mode: netserver.

## Steps to reproduce

example configuration:
```
mode: netclient
shutdown_host: 'false'
remote_ups_name: myups
remote_ups_host: 192.168.1.90
remote_ups_user: hassmon
remote_ups_password: redacted
```

## Proposed changes

Update schema to depend on mode.

**Comment by sinclairpaul** [comment]
This is enforced by the functionality of HA itself.  It is noted in the documentation at <https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#option-remote_ups_password>
