### ISSUE TITLE
Cannot use Synology ups logins because pwned

### ISSUE THREAD

**Issue by JohannCR** [hassio-addons/addon-nut#165]
# Problem/Motivation

> (Why the issue was filed)

Trying to use the nut addon with Synology ups server.
Thing is the default logins for the ups server are 'upsmon'  and 'secret' which is obviously pwned...

## Expected behavior

> (What you expected to happen)

Need to use those logins to connect to ups server (even if they were pwned isn't it more secure than user admin Synology logins ?)

## Actual behavior

> (What actually happened)

Configuration stops the plugin because of the pwn

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Please see the documentation option:

https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#option-i_like_to_be_pwned

Although it appears to be you are trying to use netclient mode, in which case no check is done by the addon.

**Comment by JohannCR** [comment]
Oh nice thanks I didn't see that !
Well 'trying' is the right word because I cannot seem to make the addon work. keep getting "No matching HID UPS found" now...
I don't know what is netclient mode I'll read some docs to find out

**Comment by sinclairpaul** [comment]
I should clarify actually, the check will still be done, but the user and password specified have no effect in netclient mode, you need to specify the remote_* options in the addon.
