### ISSUE TITLE
APC Back-UPS ES 700VA - failed - Data stale

### ISSUE THREAD

**Issue by Obscurax** [hassio-addons/addon-nut#181]
# Problem/Motivation

APC Back-UPS ES 700VA loses connection after random time. 
My hassio instance is running virtualised on an ESXi host. 
Before switching to NUT, the UPS was connected to a Windows Host with apcupsd on the same USB port without problems.

I've been looking at the previous GitHub issues and found similar issues so I tried several configs but they all end up not working.
With the default settings the connection seems to last the longest.

Settings I tried:
pollinterval = 15
pollinterval = 30
upsd_maxage: 25
upsmon_deadtime: 25

## Expected behavior

UPS connection does not drop.

## Actual behavior

30123.215582	Poll UPS [UPS@localhost] failed - Data stale
30128.216558	Poll UPS [UPS@localhost] failed - Data stale
30133.217299	Poll UPS [UPS@localhost] failed - Data stale
30138.218203	Poll UPS [UPS@localhost] failed - Data stale
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4

## Steps to reproduce

My config now:
users:
  - username: x
    password: x
    instcmds:
      - all
    actions: []
devices:
  - name: UPS
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 30
mode: netserver
shutdown_host: 'false'
list_usb_devices: true

Any advice to get a stable connection is welcome.

**Comment by zeekens** [comment]
I experience the same problem with this exact UPS. It just randomly disconnects. I have to restart the driver to get it back up again,

**Comment by Obscurax** [comment]
Changing the USB device to USB 3 in ESXi has fixed the issue. Thanks.

**Comment by Wh1terat** [comment]
@Obscurax 
This has been driving my crazy, would never have crossed my mind to swap the usb controller in esxi!
Thank you 😄
