### ISSUE TITLE
Fatal Error Unusable Configuration

### ISSUE THREAD

**Issue by JohnnySSH** [hassio-addons/addon-nut#182]
# Problem/Motivation

NUT will not work when set in client mode

## Expected behavior

I should be able to connect to my NUT server on a different system

## Actual behavior

Using Trace debug I get this output in the log:

   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000114	Using power down flag file /etc/killpower
   0.000191	Unable to use old-style MONITOR line without a username
   0.000197	Convert it and add a username to upsd.users - see the documentation
   0.000199	Fatal error: unusable configuration
[01:32:29] TRACE: bashio::config.equals: mode netserver
[01:32:29] TRACE: bashio::config: mode
[01:32:29] TRACE: bashio::jq: /data/options.json if (.mode == null) then
            null
        elif (.mode | type == "string") then
            .mode // empty
        elif (.mode | type == "boolean") then
            .mode // false
        elif (.mode | type == "array") then
            if (.mode == []) then
                empty
            else
                .mode[]
            end
        elif (.mode | type == "object") then
            if (.mode == {}) then
                empty
            else
                .mode
            end
        else
            .mode
        end
[01:32:29] TRACE: bashio::var.equals: netclient netserver
[01:32:29] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000108	Using power down flag file /etc/killpower
   0.000165	Unable to use old-style MONITOR line without a username
   0.000170	Convert it and add a username to upsd.users - see the documentation
   0.000171	Fatal error: unusable configuration
Network UPS Tools upsmon 2.7.4

## Steps to reproduce

users:
  - username: ''
    password: ''
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: []
mode: netclient
shutdown_host: 'false'
log_level: trace
remote_ups_host: RemoteNUT
remote_ups_name: myUPS
remote_ups_user: RmoteNUTuserName
remote_ups_password: RemoteNUTPassword

## Proposed changes

I have found this topic which seems to be of a similar nature:

https://github.com/instantlinux/docker-tools/issues/2

Though I have checked the output files created by the entrypoint.sh script, upsmon.conf and all details are in there and correct.

Something is strange somewhere....

**Comment by sinclairpaul** [comment]
You need to specify a user, as per the docs:

```Note: When using the remote option, the user and device options must still be present, however they will have no effect```

**Comment by JohnnySSH** [comment]
I just added a user now. Same uname/pass as the remote instance. Unfortunately the result is the same:

[01:55:50] TRACE: bashio::var.equals: netclient netserver
[01:55:50] TRACE: bashio::var.equals: netclient netserver
[01:55:50] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000243	Using power down flag file /etc/killpower
   0.000301	Unable to use old-style MONITOR line without a username
   0.000306	Convert it and add a username to upsd.users - see the documentation
   0.000308	Fatal error: unusable configuration
Network UPS Tools upsmon 2.7.4


I just wanted to test with a different user too, so I added a bogus uname/pass to the top:

users:
  - username: bla
    password: bla
    instcmds:
      - all
      -
unfortunately the result is the same :(

I have also read this for reference:

https://community.home-assistant.io/t/configuring-nut-integration-to-monitor-remote-nut-servers-pre-0-108-7/186156

**Comment by sinclairpaul** [comment]
Please post the full startup log with log_level set to info.  Also please post your config in a code block, so we can view the indentation.

**Comment by JohnnySSH** [comment]
Here's the startup log:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: Arch Linux  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[14:59:36] INFO: Setting mode to netclient...
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:59:37] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000166	Using power down flag file /etc/killpower
   0.000223	Unable to use old-style MONITOR line without a username
   0.000226	Convert it and add a username to upsd.users - see the documentation
   0.000227	Fatal error: unusable configuration
Network UPS Tools upsmon 2.7.4
[14:59:38] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000282	Using power down flag file /etc/killpower
Network UPS Tools upsmon 2.7.4
   0.000492	Unable to use old-style MONITOR line without a username
   0.000500	Convert it and add a username to upsd.users - see the documentation
   0.000501	Fatal error: unusable configuration`


The config is this:

`users:
  - username: bla
    password: bla
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: []
mode: netclient
shutdown_host: 'false'
log_level: info
remote_ups_host: <ip_address>
remote_ups_name: <ups_name>
remote_ups_user: <remote_nut_username>
remote_ups_password: <remote_nut_password>`

**Comment by JohnnySSH** [comment]
Using your example data I get this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------

 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: Arch Linux  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[15:22:30] INFO: Setting mode to netclient...
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:22:30] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000281	Using power down flag file /etc/killpower
   0.000339	UPS: ups@test (slave) (power value 1)
   0.000361	debug level is '1'
   0.000363	Warning: running as one big root process by request (upsmon -p)
   0.000480	Init SSL without certificate database
   0.033892	Trying to connect to UPS [ups@test]
   0.055124	UPS [ups@test]: connect failed: Connection failure: Connection refused
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
```


I think the error is stemming from:

`remote_ups_host: test`

I have the IP address of the remote host set. I tried inputting the fqdn of the remote nut server and also had the same issue.

somehow I need to put:

`remote_ups_host: 123.123.123.123`

**Comment by sinclairpaul** [comment]
```
[10:38:29] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000109	Using power down flag file /etc/killpower
   0.000174	UPS: ups@10.10.10.10 (slave) (power value 1)
   0.000189	debug level is '1'
   0.000191	Warning: running as one big root process by request (upsmon -p)
   0.000284	Init SSL without certificate database
   0.001068	Trying to connect to UPS [ups@10.10.10.10]
  31.540523	UPS [ups@10.10.10.10]: connect failed: Connection failure: Connection timed out
```

```
remote_ups_host: 10.10.10.10
remote_ups_name: ups
remote_ups_user: user
remote_ups_password: password
```

**Comment by JohnnySSH** [comment]
Now it fails, with "remote_ups_host" set as: 10.10.10.10

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: Arch Linux  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[15:42:14] INFO: Setting mode to netclient...
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:42:14] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000199	Using power down flag file /etc/killpower
   0.000256	Unable to use old-style MONITOR line without a username
   0.000273	Convert it and add a username to upsd.users - see the documentation
   0.000275	Fatal error: unusable configuration
Network UPS Tools upsmon 2.7.4
[15:42:15] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000083	Using power down flag file /etc/killpower
Network UPS Tools upsmon 2.7.4
   0.000138	Unable to use old-style MONITOR line without a username
   0.000142	Convert it and add a username to upsd.users - see the documentation
   0.000144	Fatal error: unusable configuration
[15:42:16] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000094	Using power down flag file /etc/killpower
   0.000155	Unable to use old-style MONITOR line without a username
   0.000157	Convert it and add a username to upsd.users - see the documentation
   0.000159	Fatal error: unusable configuration
Network UPS Tools upsmon 2.7.4
```


Checking the upsmon.conf file that is created from the scripts:

```
SHUTDOWNCMD  "s6-svscanctl -t /var/run/s6/services"
MONITOR ups@10.10.10.10 1 user password slave
DEADTIME 15
```

This is really weird!!

**Comment by sinclairpaul** [comment]
At a guess you have a # in the password then.

Not much we can do about that, its going to see it as a comment in the file.  You may be able to escape it.

Either way there isn't anything we can fix here for it.

**Comment by JohnnySSH** [comment]
> At a guess you have a # in the password then.
> 
> Not much we can do about that, its going to see it as a comment in the file. You may be able to escape it.
> 
> Either way there isn't anything we can fix here for it.

*Had :-)

I discovered that and changed the password accordingly. Now all is working fine.

Thanks for the help. It enabled me to get things working and at least track down the issue. I really appreciate it!

**Comment by sinclairpaul** [comment]
Glad you got it resolved, closing out.
