### ISSUE TITLE
Enabling TrippLite 3024

### ISSUE THREAD

**Issue by cromulus** [hassio-addons/addon-nut#185]
# Problem/Motivation

I have a TrippLite 3024 and I have gotten it to work with nuts as a standalone daemon running on a dedicated machine. I had to do some finagling of the config. 

It does not work by default, however, with this add-on.

## Expected behavior

I expect that my UPS will be configured and managed by the addon

## Actual behavior

this is the error I receive:
```
This TrippLite device (09ae:3024) is not (or perhaps not yet) supported
by usbhid-ups. Please make sure you have an up-to-date version of NUT. If
this does not fix the problem, try running the driver with the
'-x productid=3024' option. Please report your results to the NUT user's
mailing list.
```
## Steps to reproduce

Have a trip-lite 3024, and use this config:
devices:
  - name: myups
    driver: usbhid-ups
    productid: 3024
    vendorid: 09ae
    port: auto
    config:
      - '-x productid=3024 vendorid = 09ae'
```
## Proposed changes

This is the solution I used to get this working on my standalone machine: https://github.com/networkupstools/nut/issues/808

**Comment by sinclairpaul** [comment]
Unfortunately you will need to fork and maintain your own copy.  The addon installs the debian packages, I'm not keen on maintaining any additional changes outside that for future maintenance reasons (udev rules are part of the package).

**Comment by cromulus** [comment]
Makes good sense. Perhaps a "run configurable init-commands after boot" option, similar to this functionality in the [node-red addon](https://github.com/hassio-addons/addon-node-red/blob/0f3e45274a91793bdbfaa3ffd99ded7c2e159a86/node-red/rootfs/etc/cont-init.d/customizations.sh)?

**Comment by sinclairpaul** [comment]
imho, it's too complicated to try and support, plus looking at the issue linked it doesn't resolve all challenges.  My best recommendation would be to try to get the support configured upstream.
