### ISSUE TITLE
Adding A Users Name - QNAP Password Issue

### ISSUE THREAD

**Issue by rcblackwell** [hassio-addons/addon-nut#193]
I've installed Network UPS Tools on HA version 2021.10.7. The install went well and I'm able to monitor the UPS attached to the HA computer. I want to add a user for my QNAP NAS. Credentials for the NAS are;

User ID: admin
P/W: 123456

If I add the necessary details to the configuration panel the log reports an error - unable to start. Seems the short password used by QNAP is the problem as the log indicates the password is on PWNED list and the services fails to start as a result.

I've tried unsuccessfully to change configuration parameters (User ID, P/W, MONITOR string) on the NAS. How can I get around this PWNED password issue so that adding the QNAP user to Network UPS Tools doesn't prevent the add-on from starting?

With appreciation

Robert

**Comment by sinclairpaul** [comment]
Does this not work for you?

https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#option-i_like_to_be_pwned

**Comment by rcblackwell** [comment]
> Does this not work for you?
> 
> https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#option-i_like_to_be_pwned

Sure does - don't know how I missed that option.

Thank you
