### ISSUE TITLE
Failure getting NUT ups alias, Socket error.

### ISSUE THREAD

**Issue by Anton-Ka** [hassio-addons/addon-nut#198]
# Problem/Motivation

After updating the component to version 0.9.0, all sensors became unavailable.
```
Logger: homeassistant.components.nut
Source: components/nut/__init__.py:212
Integration: Network UPS Tools (NUT) (documentation, issues)
First occurred: 11 ноября 2021 г., 23:56:21 (9 occurrences)
Last logged: 00:03:55

Failure getting NUT ups alias, Socket error.
```

## Expected behavior

Before the update, everything worked smoothly.

## Actual behavior

I lost data from my ups.

## Steps to reproduce

I don't know.
The log file does not show any problems.
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2021.10.7
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[00:08:44] INFO: Setting mode to netserver...
[00:08:45] INFO: Generating /etc/nut/upsd.users...
[00:08:47] INFO: Configuring user: ha
[00:08:48] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[00:08:52] INFO: Configuring Device named myups...
[00:08:52] INFO: Starting the UPS drivers...
```

## Proposed changes

I would like everything to work as before.

**Comment by Anton-Ka** [comment]
My config integration:
```
devices:
  - name: myups
    driver: blazer_usb
    port: /dev/bus/usb/001/006
    config: []
mode: netserver
shutdown_host: 'false'
users:
  - username: **
    password: **
    instcmds:
      - all
    actions: []
```

**Comment by sinclairpaul** [comment]
The addon appears to be functioning, so this looks to be an issue with the integration, how do you have that configured?

**Comment by Anton-Ka** [comment]
> The addon appears to be functioning, so this looks to be an issue with the integration, how do you have that configured?

Earlier I clicked the + (add integration) button and added it.  it worked for a long time without any problems.
Now:
![Screenshot_20211112-010206](https://user-images.githubusercontent.com/74901464/141375730-530afaa4-095a-450d-95c5-65dc06660f45.jpg)

**Comment by sinclairpaul** [comment]
This isn't an addon issue, as its running.

I would suggest removing and re-adding the integration, if that still fails seek help on the HA discord/forums, or log an issue against the integration.

**Comment by Anton-Ka** [comment]
> This isn't an addon issue, as its running.
> 
> I would suggest removing and re-adding the integration, if that still fails seek help on the HA discord/forums, or log an issue against the integration.

I don't know what exactly the problem is.  I removed the integration and try to install it again, but when I try to connect, I get the message "Failed to connect."
![Screenshot_20211112-090919__01](https://user-images.githubusercontent.com/74901464/141419481-3bd12205-26ee-421d-8bbd-61aa6302b2ac.jpg)

I will clarify that this problem appeared after updating the addon.

I will clarify that this problem appeared after updating the addon.

**Comment by sinclairpaul** [comment]
From your log:

`[00:08:47] INFO: Configuring user: ha`

**Comment by Anton-Ka** [comment]
> From your log:
> 
> `[00:08:47] INFO: Configuring user: ha`

When i logged i used this name.  Later I gave a different name, suggesting that it was too simple.
