### ISSUE TITLE
broken update driver connection

### ISSUE THREAD

**Issue by dodor87** [hassio-addons/addon-nut#200]
After update al last version 0.9

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.11.4
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[11:56:02] INFO: Setting mode to netserver...
[11:56:02] INFO: Generating /etc/nut/upsd.users...
[11:56:03] INFO: Configuring user: xxxx
[11:56:03] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[11:56:05] INFO: Configuring Device named ups_rpi...
[11:56:05] INFO: Starting the UPS drivers...
Supported UPS detected with megatec/old protocol
Rating information unavailable
Startup timer elapsed, continuing...
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

With old version 0.8 work correclty

**Comment by sinclairpaul** [comment]
There isn't a change to NUT itself within the latest release, are you saying if you roll back to the previous version it functions as expected?

Can you please post your config?

**Comment by DanDon** [comment]
I have the same issue with the new release too ??

my config is:

`devices:
  - name: UPS1
    driver: usbhid-ups
    port: auto
    config: []
  - name: UPS2
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'
users:
  - username: ups
    password: aaffaa2323
    instcmds:
      - all
    actions: []`

I have 2 x CyberPower UPS devices connected via USB to the HA host...

If I restart HA then the supervisor load correctly the first time and the integration loads both the UPS devices okay .... but within a day they will fail with the error that @dodor87 also has ??

**Comment by sinclairpaul** [comment]
@DanDon I doubt your error is the same, as you have a different model of UPS, please create a seperate issue with your logs, however before you do, I would suggest you look at the previous issues logged for Cyberpower devices, in particular the config for polling:

```
devices:
  - name: Cyberpower
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 15
mode: netserver
shutdown_host: 'false'
upsd_maxage: 25
upsmon_deadtime: 25
```

**Comment by DanDon** [comment]
@sinclairpaul 
Thanks for the response but from what I can see I do get the same issue ... this is the problem:

```
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[18:25:30] INFO: Setting mode to netserver...
[18:25:30] INFO: Generating /etc/nut/upsd.users...
[18:25:30] INFO: Configuring user: ups
[18:25:30] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[18:25:30] INFO: Configuring Device named UPS1...
[18:25:30] INFO: Configuring Device named UPS2...
[18:25:30] INFO: Starting the UPS drivers...
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
No matching HID UPS found
USB communication driver 0.33
Driver failed to start (exit status=1)
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
No matching HID UPS found
Driver failed to start (exit status=1)
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

This is with your config of the devices above or with the standard config I posted earlier...

Thanks for your response

**Comment by DanDon** [comment]
This is what heppens before I have to reboot the host to fix....

```
25.155198	Data for UPS [UPS1] is stale - check driver
  25.005440	Poll UPS [UPS1@localhost] failed - Data stale
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
  30.005919	Poll UPS [UPS1@localhost] failed - Data stale
  35.006417	Poll UPS [UPS1@localhost] failed - Data stale
  40.007938	Poll UPS [UPS1@localhost] failed - Data stale
  45.008207	Poll UPS [UPS1@localhost] failed - Data stale
  50.008856	Poll UPS [UPS1@localhost] failed - Data stale
  55.009360	Poll UPS [UPS1@localhost] failed - Data stale
  60.009874	Poll UPS [UPS1@localhost] failed - Data stale
  65.010263	Poll UPS [UPS1@localhost] failed - Data stale
  70.011184	Poll UPS [UPS1@localhost] failed - Data stale
  75.012228	Poll UPS [UPS1@localhost] failed - Data stale
  80.012683	Poll UPS [UPS1@localhost] failed - Data stale
  85.013180	Poll UPS [UPS1@localhost] failed - Data stale
  90.013699	Poll UPS [UPS1@localhost] failed - Data stale
  95.014229	Poll UPS [UPS1@localhost] failed - Data stale
 100.014532	Poll UPS [UPS1@localhost] failed - Data stale
 105.015072	Poll UPS [UPS1@localhost] failed - Data stale
 110.015614	Poll UPS [UPS1@localhost] failed - Data stale
 115.016070	Poll UPS [UPS1@localhost] failed - Data stale
 120.016636	Poll UPS [UPS1@localhost] failed - Data stale
 125.017107	Poll UPS [UPS1@localhost] failed - Data stale
 130.017565	Poll UPS [UPS1@localhost] failed - Data stale
 135.017889	Poll UPS [UPS1@localhost] failed - Data stale
 140.018558	Poll UPS [UPS1@localhost] failed - Data stale
```

**Comment by CalebFenton** [comment]
You might find more clues digging around closer to the nut-server github, e.g. 
* https://github.com/instantlinux/docker-tools/issues/14 (specifically)
* https://github.com/networkupstools/nut

**Comment by sinclairpaul** [comment]
Closing as no response from original reporter.
