### ISSUE TITLE
Can't use two apc ups units at once

### ISSUE THREAD

**Issue by jatgm1** [hassio-addons/addon-nut#201]
# Problem/Motivation
When adding two devices it only shows one device despite the integrations page showing two instances and two devices
> (Why the issue was filed)

## Expected behavior
Having two ups units
> (What you expected to happen)

## Actual behavior
Having one ups units that is mislabeled as another
> (What actually happened)

## Steps to reproduce
Add two ups's with the default configuration on auto in configuration in the addon in supervisor in home assistant
> (How can someone else make/see it happen)

## Proposed changes
I have no idea
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Post logs and config.

Don't use "auto" for multiple devices, you will need to set config as per the docs https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#sub-option-config

**Comment by jatgm1** [comment]
How do I find a vendor Id or something identifying and then like specify it? Is there an option for finding something to use to identify it?

**Comment by jatgm1** [comment]
Both devices are literally basically identical so I think I need something to identify them

**Comment by sinclairpaul** [comment]
https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#option-list_usb_devices

**Comment by jatgm1** [comment]
Bus 001 Device 004: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 001 Device 003: ID 10c4:8a2a Silicon Labs HubZ Smart Home Controller
Bus 001 Device 005: ID 051d:0002 American Power Conversion Uninterruptible Power 

So they both have the same "Id" so how do I identify it? Is it possible to use the device number or whatever that is?
