### ISSUE TITLE
No way to connect two devices that are identical

### ISSUE THREAD

**Issue by jatgm1** [hassio-addons/addon-nut#203]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
Not sure why the issue was closed because there literally doesn't appear to be a way to specify which devices to use if both devices are identical. I'm not sure which rule I violated or whatever.

**Comment by sinclairpaul** [comment]
It was closed because it was converted to a discussion, which is stated in the issue.

https://github.com/hassio-addons/addon-nut/discussions/202
