### ISSUE TITLE
NUT crash RaspPi3 if connected when booting

### ISSUE THREAD

**Issue by MatteGary** [hassio-addons/addon-nut#205]
Hi, I'm experiencing the following issue: if my Raspberry Pi 3 boots up with the ups connected through USB, it will not boot completely and HomeAssistant will not start. If I then unplug USB and perform a power cycle, everything works fine.
What kind of info can I collect to help you in investigating this?
 
System info:
Network UPS Tools v0.9.0
Home Assistant OS v 6.6
Core v core-2021.11.4
Supervisor v supervisor-2021.10.8

**Comment by sinclairpaul** [comment]
I don't see how this is related to the addon, hardware is managed by the OS and Supervisor.

I would suggest seeking help with Home Assistant itself.
