### ISSUE TITLE
Netclient mode failed - got [ERROR ACCESS-DENIED]

### ISSUE THREAD

**Issue by degrashopper** [hassio-addons/addon-nut#208]
# Problem/Motivation

When I configure the addon as netclient to connect to the master it fails. When I setup the nut integration (not the addon) with the same credentials it works. Also a docker container (on a different machine) that can connect to the master works with the same credentials.

## Expected behavior

the addon should be able to connect to the master

## Actual behavior

in the logging the process stops on the message: failed - got [ERROR ACCESS-DENIED]

## Steps to reproduce

addon configuration

devices:
  config: []
    driver: usbhid-ups
    name: apc
    port: auto
mode: netclient
shutdown_host: 'false'
users:
  actions: []
    instcmds:
        all
    password: '!secret apc_password'
    username: admin
remote_ups_name: apc
remote_ups_host: 192.168.2.110
remote_ups_user: admin
remote_ups_password: '!secret apc_password'

addon Logging
[21:35:34] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000313	Using power down flag file /etc/killpower
   0.000490	UPS: apc@192.168.2.110 (slave) (power value 1)
   0.000634	debug level is '1'
   0.000754	Warning: running as one big root process by request (upsmon -p)
   0.000999	Init SSL without certificate database
   0.001915	Trying to connect to UPS [apc@192.168.2.110]
   0.002814	Login on UPS [apc@192.168.2.110] failed - got [ERR ACCESS-DENIED]

## Proposed changes
--

**Comment by degrashopper** [comment]
> As a suggestion, try a password without special characters in it, due to the way it is piped into the config file it may have issues with certain characters.

@sinclairpaul The password is allready without special characters.

**Comment by degrashopper** [comment]
Could it be that the addon tries to use ssl where the server don't? logging shows 0.000999 Init SSL without certificate database.

**Comment by sinclairpaul** [comment]
> Could it be that the addon tries to use ssl where the server don't? logging shows 0.000999 Init SSL without certificate database.

No

Please consult the logs of your NUT server, this is likely configuration.

**Comment by degrashopper** [comment]
> > Could it be that the addon tries to use ssl where the server don't? logging shows 0.000999 Init SSL without certificate database.
> 
> No
> 
> Please consult the logs of your NUT server, this is likely configuration.

Okay i will look at those this weekend. But i don't think it is the server. The nut integration and the docker container of teknologist/webnut connect just fine with the server.

**Comment by degrashopper** [comment]
@sinclairpaul could you tell me where i could find the net-server logs? or how i can create them? nut-server is installed on debian 11. I could find something about upslog and that is running now but i don't think that is logging issues about the nut-server itself.

**Comment by sinclairpaul** [comment]
/var/log/syslog at a guess, but I would suggest looking at the NUT documentation.

**Comment by degrashopper** [comment]
Okay thanks. according to the documentation upslog is the log daemon.

**Comment by degrashopper** [comment]
when I fire up the nut addon I can't see anything regarding connection issues in the syslog or nutlog on the nut-server.

**Comment by degrashopper** [comment]
Maybe somebody else could test the netclient setup to confirm the issue?

**Comment by degrashopper** [comment]
When I restart the services on the master while the nut addon is running the addon is picking up the events. So something seems to work.

 590.066364	Login on UPS [apc@192.168.2.110] failed - got [ERR ACCESS-DENIED]
 595.067099	Poll UPS [apc@192.168.2.110] failed - Driver not connected
 600.067376	Poll UPS [apc@192.168.2.110] failed - Driver not connected
 605.068233	Poll UPS [apc@192.168.2.110] failed - Driver not connected
 610.069185	Poll UPS [apc@192.168.2.110] failed - Driver not connected
 615.070106	Poll UPS [apc@192.168.2.110] failed - Driver not connected
 620.071396	Poll UPS [apc@192.168.2.110] failed - Driver not connected
 625.071728	Poll UPS [apc@192.168.2.110] failed - Driver not connected
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4

**Comment by degrashopper** [comment]
@sinclairpaul the nut addon is running now for 3 days in netclient mode without problems. Only at the startup of the container i got the message [ERR ACCESS-DENIED]. After that the events are working  in HA so I think it is just a bug in the addon regarding the [ERR ACCESS-DENIED] message when running netclient mode.
