### ISSUE TITLE
UPS not view

### ISSUE THREAD

**Issue by manustars** [hassio-addons/addon-nut#213]
# Problem/Motivation
The my ups connect on usb to HA virtual machine not work .

I state that with this configuration previously it worked. on ha i see ups correctly but on nut i get this log

HA UPS
[ 5926.324242] usb 2-2.1: Product: Eaton 5P
[ 5926.324243] usb 2-2.1: Manufacturer: EATON

NUT LOG
No matching HID UPS found
Driver failed to start (exit status=1)
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by saxopwn** [comment]
Getting the same issue!

**Comment by manustars** [comment]
the issu not resolve. my ha install is ova for vmware esxi 6.7 and ups is connect to usb hypervisor

**Comment by avbfr** [comment]
Same Issue here...

**Comment by sinclairpaul** [comment]
Set the following option <https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#option-list_usb_devices>

Ensure your ups is listed as a valid device.  Also try USB2/3 ports and confirm the cables.  Also ensure your device is listed as supported on the main NUT documentation.

Please do not add comments as "Same Issue".

**Comment by avbfr** [comment]
Thx for your answer but my APC used to work well until a few weeks. 
UPDATE: I juste made a bunch of tests and It looks like the USB port of my APC no longer works. 
The issue is on my side. Sorry about that.

**Comment by sinclairpaul** [comment]
From that log you didn't set the option, as it would show the devices connected.

> on the esxi server the ups is connected to vm and HA see them

What do you mean HA see's the device?, try changing the port in ESX to be USB 2 or 3.

This really sounds like a hardware/hypervisor issue.

**Comment by manustars** [comment]
this configuration:
`devices:
  - name: UPS Server
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 0463
mode: netserver
shutdown_host: 'false'
users:
  - actions: []
    instcmds:
      - all
    password: password
    username: user
list_usb_divices: true`
 
and this via cli ha:
[core-ssh ~]$ ha hardware info  | grep EATON
    ID_SERIAL: EATON_Eaton_5P_P111J07GM8
    ID_VENDOR: EATON
    ID_VENDOR_ENC: EATON

**Comment by sinclairpaul** [comment]
```list_usb_divices: true``` should be ```list_usb_devices: true```

Also please post your config with formatting.

**Comment by manustars** [comment]
corrected my oversight now you see the ups

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 047: ID 0463:ffff MGE UPS Systems UPS
Bus 002 Device 003: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 002 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
[22:28:03] INFO: Generating /etc/nut/upsd.users...
[22:28:03] INFO: Configuring user: manustar
[22:28:04] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[22:28:04] INFO: Configuring Device named UPS Server...
[22:28:04] INFO: Starting the UPS drivers...
Error: no UPS definitions found in ups.conf
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

> 

I don't know how I can put the formatting

devices:
  - name: UPS Server
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 0463
mode: netserver
shutdown_host: 'false'
users:
  - actions: []
    instcmds:
      - all
    password: password
    username: username
list_usb_devices: true

**Comment by sinclairpaul** [comment]
This:

```Error: no UPS definitions found in ups.conf```

Suggests it's a formatting issue, and is a different error from first reported.

Try the following config:

```
users:
  - username: myuser
    password: changeme
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: "false"

```

The space in the name you had will likely cause an issue.

You can format text by wrapping it in three backticks ```

**Comment by manustars** [comment]
i test the config but when i save on addon change to this:
```
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'
users:
  - username: user
    password: pass
    instcmds:
      - all
    actions: []
```
and recive the same error

**Comment by manustars** [comment]
and use the default cfg recive this:

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[22:59:38] INFO: Setting mode to netserver...
[22:59:38] INFO: Generating /etc/nut/upsd.users...
[22:59:38] INFO: Configuring user: user
[22:59:39] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[22:59:39] INFO: Configuring Device named myups...
[22:59:39] INFO: Starting the UPS drivers...
No matching HID UPS found
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
Driver failed to start (exit status=1)
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by sinclairpaul** [comment]
Then the driver cannot communicate with the UPS correctly, please try as suggested before changing between USB 2/3 and possibly a different cable.

There is nothing we can do here from an addon perspective, it is configuration from the hypervisor/system itself.

**Comment by manustars** [comment]
but its possible connect via network? the eaton 5p have and additional network card

**Comment by manustars** [comment]
i test 2 usb cable and all usb port, but the result is same.

its possible configure nut for view ipm?
