### ISSUE TITLE
Warnings in Supervisor log

### ISSUE THREAD

**Issue by nepozs** [hassio-addons/addon-nut#214]
# Problem/Motivation

> "Please report this to the maintainer of Network UPS Tools" in log

## Expected behavior

> No warnings

## Actual behavior

> Warnings in Supervisor logs

## Steps to reproduce

> none, it just happens after update some time ago (I don't remember version)

```22-01-26 12:23:53 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Network UPS Tools
22-01-26 12:23:53 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Network UPS Tools
22-01-26 12:23:53 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/8798f11b/nut/config.json: required key not provided @ data['arch']. Got None```

**Comment by sinclairpaul** [comment]
This isn't referring to this addon (8798f11b isn't the hash of this repo), please check where you installed it from and report there.

**Comment by nepozs** [comment]
It isn't installed at all, but only one reference in Store is to THIS repository.
