### ISSUE TITLE
/dev/ttyUSB0 is locked by another process

### ISSUE THREAD

**Issue by flowchartsman** [hassio-addons/addon-nut#215]
# Problem/Motivation
I'm running hassos via proxmox and passing through my entire USB bus to the hassos VM.

I have a APC UPS attached to hassos via an FTDI serial adapter plugged into the UPSs special cable. Thus I'm using the `apcsmart` driver, and pointing it at the port `/dev/ttyUSB0`:

```yaml
devices:
  - config: []
    driver: apcsmart
    name: apc
    port: /dev/ttyUSB0
mode: netserver
shutdown_host: 'false'
users:
  - username: <nut user>
    password: <nut user pass>
    instcmds:
      - all
    actions: []
list_usb_devices: false
```
I got this to work when using plain USB passthrough, but for some reason it says that `/dev/ttyUSB0` is "locked by another process":

```
[00:25:23] INFO: Setting mode to netserver...
[00:25:23] INFO: Generating /etc/nut/upsd.users...
[00:25:23] INFO: Configuring user: nut
[00:25:23] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[00:25:23] INFO: Configuring Device named apc...
[00:25:24] INFO: Starting the UPS drivers...
/dev/ttyUSB0 is locked by another process
Driver failed to start (exit status=1)
Network UPS Tools - APC Smart protocol driver 3.1 (2.7.4)
APC command table version 3.1
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
```
But there are no lockfiles present for this device, and `fuser /dev/ttyUSB0` shows nothing. Am I missing something here? I can think of no reason why this would be locked

## Expected behavior

NUT service initializes

## Actual behavior

(as above)

**Comment by flowchartsman** [comment]
Worth noting: I originally had all usb devices plugged into a powered hub; upon removing this and plugging them directly into the box and restarting homeassistant, the addon worked again.

Not sure why this would be the case, but I'm noting it here in case anyone can explain to me why a powered hub would cause this.

**Comment by sinclairpaul** [comment]
Unfortunately no idea why your hardware doesn't function that way, I would suggest seeking more information on the HA forums or Discord.

As this isn't an issue relating to the addon, and we use Github for tracking issues, I will close this out.
