### ISSUE TITLE
NUT Integration started but entities unavailable. 

### ISSUE THREAD

**Issue by bsmith05** [hassio-addons/addon-nut#224]
# Problem/Motivation

> Entities from the NUT (0.10.0) integration go to an 'unavailable' state.  

HASSOS Log: 
Logger: homeassistant.components.nut
Source: helpers/update_coordinator.py:222
Integration: Network UPS Tools (NUT) ([documentation](https://www.home-assistant.io/integrations/nut), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+nut%22))
First occurred: April 27, 2022, 11:00:58 AM (**58 occurrences**)
Last logged: 12:25:58 PM
Error fetching NUT resource status data: Error fetching UPS state

NUT Integration Log:
[08:03:01] INFO: Configuring Device named myups...
[08:03:01] INFO: Starting the UPS drivers...
Using subdriver: APC HID 0.96
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:03:02] INFO: Starting the UPS information server...
   0.000000	fopen /run/nut/upsd.pid: No such file or directory
   0.000970	listening on 0.0.0.0 port 3493
   0.001368	Connected to UPS [myups]: usbhid-ups-myups
[08:03:02] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000349	Using power down flag file /etc/killpower
   0.000638	UPS: myups@localhost (master) (power value 1)
   0.000864	debug level is '1'
   0.000878	Warning: running as one big root process by request (upsmon -p)
   0.001210	Init SSL without certificate database
   0.006114	Trying to connect to UPS [myups@localhost]
   0.516932	User upsmonmaster@127.0.0.1 logged into UPS [myups]
   0.007742	Logged into UPS myups@localhost
15735.893502	Data for UPS [myups] is stale - check driver
15736.381605	Poll UPS [myups@localhost] failed - Data stale
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
15741.389031	Poll UPS [myups@localhost] failed - Data stale
15746.389632	Poll UPS [myups@localhost] failed - Data stale
15751.390158	Poll UPS [myups@localhost] failed - Data stale
15756.390489	Poll UPS [myups@localhost] failed - Data stale
15761.390997	Poll UPS [myups@localhost] failed - Data stale
15766.391509	Poll UPS [myups@localhost] failed - Data stale
15771.391946	Poll UPS [myups@localhost] failed - Data stale
15776.392459	Poll UPS [myups@localhost] failed - Data stale
15781.392970	Poll UPS [myups@localhost] failed - Data stale
15786.393644	Poll UPS [myups@localhost] failed - Data stale
15791.394123	Poll UPS [myups@localhost] failed - Data stale

NUT Configuration:
- config: []
  driver: usbhid-ups
  name: myups
  port: auto

users:
- actions: []
  instcmds:
    - all
  password: <redacted>
  username: <redacted>

Scan Interval: 60seconds
Host: a0d7b954-nut:3493

## Expected behavior

> The entities from the NUT integration should remain alive as long as the integration is started.  They should be unavailable if the host is down, physical connection to UPS is disconnected or integration is gracefully or forcefully stopped.

## Actual behavior

> The NUT integration starts normally, and entities show proper UPS values.  After a period of time (exact timing is unknown) the NUT integration goes from a functioning to non-functioning state. Non-Functioning state is defined as Integration is started and running but entities report 'unavailable' states. Restarting the NUT integration resolves the problem, until it happens the next time.  Have observed this happening up to 5 times a day. I monitored the count by sending myself a state changed notification for each time the entities changed state to 'unavailable'. 

>Rebooting Host solves the problem temporarily. Entities eventually go back to 'unavailable'.
>Reinstalling the NUT integration does not resolve the problem.

## Steps to reproduce

> Configure the NUT integration and let it run.  Entities eventually go 'unavailable'.  Restart the integration and entities will eventually go 'unavailable'.

>UPS Model: APC Back-UPS XS 1300G
>Host: VMware ESXI 7.0.1, USB 2.0 Passthrough
>Home Assistant Core: core-2022.4.7
>Home Assistant Supervisor: supervisor-2022.05.0 
>Home Assistant OS: 7.6

>Watchdog is enabled. Since the NUT integration is technically started, Watchdog doesnt ever trigger a restart.

## Proposed changes

> I would prefer the NUT Integration provide additional information about why it's failing to communicate with the UPS or fix the problem outright.

> My workaround was to create a Node-Red flow to restart the integration when the entity states change to 'unavailable'. It works pretty well.  I have a push notification to notify me when the flow triggers a restart.

**Comment by bsmith05** [comment]
Bump. Anyone else having this issue?

**Comment by pmorange** [comment]
Same happening to me.
Goes to Unavailable randomly, and also each time I power up my main computer that is powered through the UPS. 
The problem might be caused by small problems in data transmission, and once it occurs I normally unplug and replug the USB cable... But restarting the addon seems easier indeed.

**Comment by bsmith05** [comment]
@pmorange - what type of ups are you using?  Also, how are you running Home Assistant(pi, ha blue, vm, etc)?  

Im curious if there are similarities between our setups.  Mine is listed above.

**Comment by pmorange** [comment]
Hi, I'm using an APC BE850G2-FR that's brand new.
I have HA as a vm in a Docker (hassio) : Home Assistant OS 8.2 / supervisor-2022.05.3

Similar yes.
Have a look at : https://www.reddit.com/r/homeassistant/comments/rk4bs1/problem_with_nuts_add_on/

I have just set up the following automation I have yet to test, to restart the addon when it begins failing: 
```
- id: '1655812573878'
  alias: Auto-restart NUT add-on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.myups_status_2
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nut
  mode: single
```

Reading the thread on reddit that I gave you, it could do the trick.

**Comment by pmorange** [comment]
I agree with you.
Although I love node-red, if it can be done directly in HA I prefer to stick to the basics :-p
It's a pain to have something so critical as a UPS not working properly, as if it becomes unavailable and power halts, HA will surely not be properly shut down.
