### ISSUE TITLE
Legrand Kerr 800 support

### ISSUE THREAD

**Issue by bubez81** [hassio-addons/addon-nut#225]
# Problem/Motivation

Can't connect the keor 800 Legrand UPS

## Expected behavior

The UPS has to work with usbhid-ups driver
## Actual behavior

The logs: No matching HID UPS found

## Proposed changes
There is a possibility to compile the nut package with this support: https://github.com/networkupstools/nut/issues/616

**Comment by thefathefa** [comment]
Maybe useful to fix the typo in the title from Keer to Keor?

**Comment by sinclairpaul** [comment]
Once the updated NUT package is in the Debian repos we will look to update.  Until then if you need to build NUT, I would suggest running your own.

**Comment by bubez81** [comment]
interesting, but how would I go about compiling a beta or patched version of nut into the addon for hassio?
