### ISSUE TITLE
Total Energy Consumed is missing

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [hassio-addons/addon-nut#227]
# Problem/Motivation
I am using NUT add-on with my two APC UPS system - conneced via network using snmp-driver.
There are a lot data provided about current, voltage and load, but I miss the information about energy, like total consumed energy (OID .1.3.6.1.4.1.318.1.1.1.4.3.6.0).

## Expected behavior
I would expect that the total consumed energy is provided so that later on a sensor can be generated for it by the HA integration.

## Steps to reproduce
No dedicated steps needed. Just use snmp-driver to obsers your UPS (e.g. APC Smart-UPS SRT 5000).

## Proposed changes
I think the above OID should be included in the queries the nut server makes to the UPS'es, however I am not an expert on the topic.

**Comment by sinclairpaul** [comment]
The addon runs the NUT software, you would need to investigate your issue upstream with that project.
