### ISSUE TITLE
'Failed to connect'

### ISSUE THREAD

**Issue by 26tajeen** [hassio-addons/addon-nut#234]
# Problem/Motivation

> No matter what I try, I get 'Failed to connect'

## Expected behavior

> That it would connect and return sensors

## Actual behavior

> That it says "failed to connect"

## Steps to reproduce

> Install addon, try to connect to any IP address 

## Proposed changes

> Unclear what's going wrong. I've tried connecting to a non-existent IP and it returned the exact same error so even just a "better" (more verbose) error message would help loads.

**Comment by 26tajeen** [comment]
![image](https://user-images.githubusercontent.com/28266789/173826045-c42cee0a-982c-40fd-a663-9603a538d60f.png)

**Comment by 26tajeen** [comment]
ah so the integration only works if you have the add-on installed? I've installed the add-on but that gives another error:

```
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[13:47:54] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[13:47:54] INFO: Setting mode to netserver...
[13:47:55] INFO: Generating /etc/nut/upsd.users...
[13:47:55] INFO: Configuring user: upsmon
[13:47:56] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[13:47:57] INFO: Configuring Device named myups...
[13:47:57] INFO: Starting the UPS drivers...
Created directory: /var/lib/snmp/cert_indexes
Startup timer elapsed, continuing...
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by frenck** [comment]
> ah so the integration only works if you have the add-on installed?

No? The integration can be used without the add-on.

This is the add-on repository, so I'm assumed you have been using the add-on; since you created an issue here.

**Comment by 26tajeen** [comment]
ah sorry. My issue then is with the integration. But then, it turns out, the add-on also isn't happy and won't start either.

**Comment by 26tajeen** [comment]
> No? The integration can be used without the add-on.

[Interesting](https://community.home-assistant.io/t/nut-network-ups-tools-myups-no-longer-reachable-2021-2-1/278688/17?u=daneboom)

**Comment by 26tajeen** [comment]
> The integration in Home Assistant supports a NUT server wherever it is running.

but you agree with @frenck that you need to have the add-on installed, right?

The add-on seems to fail/stop at the "Starting the UPS drivers..." point

**Comment by sinclairpaul** [comment]
The service is timing out connecting to your network device.

Please ensure that the device is supported by the version of NUT that is running in the addon via SNMP.

**Comment by 26tajeen** [comment]
I'd be amazed if support for it had been dropped. I was using Home Assistant NUT to monitor my UPS until my SD card died and I'm just rebuilding everything I had added since my last backup in March. I must have added NUT to my HA in April sometime

**Comment by 26tajeen** [comment]
@sinclairpaul - the device is definitely supported because I was previously running a version of NUT from 2019 and it worked. Now I'm using the latest available NUT in 2022 and it's not working. NO config at all has changed on the NUT server (another Pi on my network), it's just the NUT client (Home Assistant) I'm struggling with. Any tips? MANY THANKS

**Comment by sinclairpaul** [comment]
I'm confused as to what you are trying to accomplish here, you have a separate NUT server and are trying to configure the addon as another server?

If you want it to be a client, configure its as a netclient, although you could just point the integration at your existing NUT server.  If you want it to be a server attaching to an SNMP device, check the logs on the device, do a MIB walk, maybe even use an SNMP sensor in HA to prove connectivity.
