### ISSUE TITLE
Won't work with Cyber Power UPSes

### ISSUE THREAD

**Issue by robbiet480** [hassio-addons/addon-nut#24]
# Problem/Motivation

Cyber Power UPSes have an annoying quirk where if a connection is not established for 20 seconds, it resets the USB interface which causes its `/dev/bus/usb` path to change. Because of that, the addon is unable to connect to them. The `/dev/bus/usb` path gets mapped in as a device, but [Docker doesn't support hot plugging USB devices](https://stackoverflow.com/a/35144100/486182), so even though the device is visible via `lsusb` it is not accessible with the `usbhid-ups` driver. 

## Expected behavior

I expected the UPS to work

## Actual behavior

The UPS doesn't work because the USB path is frequently reset until a successful connection is made.

## Steps to reproduce

1. Have a Cyber Power UPS
2. Try using this addon
3. See that startup will never properly complete

## Proposed changes

It's possible this can be fixed by setting `full_access` / `privileged` to True and mapping in `/dev/bus/usb` as a volume in addition to the existing device. I've tried adding udev rules on the host to map the UPS to `/dev/ups0` to give Docker a stable device path but it seems as soon as the UPS resets that symlink is lost until it reconnects and Docker will never re-attach properly

**Comment by sinclairpaul** [comment]
Just to add, may only be applicable to slower performing devices, so we need to validate on a Pi3

**Comment by robbiet480** [comment]
FYI I was running on a Pi 4

**Comment by robbiet480** [comment]
Found a good resource [here](http://marc.merlins.org/perso/linux/post_2018-12-20_Accessing-USB-Devices-In-Docker-_ttyUSB0_-dev-bus-usb-_-for-fastboot_-adb_-without-using-privileged.html)

**Comment by robbiet480** [comment]
[Here's the exact issue we are hitting](https://github.com/home-assistant/supervisor/issues/331)

**Comment by robbiet480** [comment]
It seems this is also fixable via [this](https://github.com/moby/moby/issues/35359#issuecomment-535560683).

**Comment by robbiet480** [comment]
Found fix not requiring supervisor hacks [here](http://www.macpczone.co.uk/content/using-libusb-linux-kernel-greater-34-and-without-udev).

```bash
#!/bin/bash

BUSSES=4

for ((b = 1;b <= BUSSES;b++))
{
    bbb=$(printf "%03d" $b)
    mkdir -p /dev/bus/usb/$bbb
    for ((d = 1;d <= 127;d++))
    {
        ddd=$(printf "%03d" $d)
        mknod /dev/bus/usb/$bbb/$ddd c 189 $((($b - 1) * 128 + ($d - 1)))
    }
}
exit 0
```
