### ISSUE TITLE
enable stdin in the addon config

### ISSUE THREAD

**Issue by fumantsu** [hassio-addons/addon-nut#244]
# Problem/Motivation

I'm trying as many others to send upscmd commands to disable the beeper over automation. After many tests, I discover that actually the possibility of using hassio.addon_stdin as action in Automations is not possible because it is not enabled in the addon the 'stdin' parameter in the config.yaml (actually doesn't exist and it is by default false). 
Enabling this will allow users to send commands via automation which especially in users with hassos is impossible with other ways.

## Proposed changes

https://developers.home-assistant.io/docs/add-ons/configuration/
stdin needs to be true and perhaps hassio_api.

**Comment by frenck** [comment]
The use case is too small to add such a thing to this add-on. This should rather be solved on the integration level (this feels more like a workaround for the fact the integration doesn't provide these controls).

Thanks for sharing your idea, but I'm going to pass on it as opening things like these comes with consequences I'm not willing to accept without strong reasoning.

../Frenck
