### ISSUE TITLE
Unable to start NUT server / terminates after a few seconds

### ISSUE THREAD

**Issue by alanpilz** [hassio-addons/addon-nut#247]
# Problem/Motivation

> When trying to start NUT Server on HA, it starts, and then unexpectedly stops running

## Expected behavior

> NUT Server should start up and remain up

## Actual behavior

> NUT Server stops abruptly, no logs are generated in NUT page

## Steps to reproduce

> Select Start.. and after a short time go back to the NUT server Add On and it shows Start

## Proposed changes

>I expect  NUT Server to remain up..

Config File

```
devices:
  - config: []
    driver: snmp-ups
    name: myups
    port: auto
mode: netserver
shutdown_host: "false"
users:
  - actions: []
    instcmds:
      - all
    password: nut
    username: `nut
```
Supervisor Logs:

``
22-08-26 18:40:10 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/nut/aarch64 with version 0.11.0
22-08-26 18:40:22 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-96610' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:959> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 965, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 129, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00
22-08-26 18:40:22 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-96612' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:959> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 965, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 129, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00
22-08-26 18:40:22 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Network UPS Tools is failed, restarting...
``

**Comment by sinclairpaul** [comment]
Looks to me you have enabled Watchdog for the addon, and as it crashes due to invalid config, it gets restarted.

You have set the snmp-ups driver but haven't configured it (port cannot be auto), you can find more information at https://networkupstools.org/docs/man/snmp-ups.html

**Comment by euggersh** [comment]
I'm experiencing the same issue.  I followed the instructions on this github repository and the related Home Assistant documentation, but it sounds from @sinclairpaul's response above that there's other documentation somewhere or some assumed knowledge required beyond what's documented for this add-on...?

**Comment by sinclairpaul** [comment]
There is no assumed knowledge, the details are documented in the NUT source documentation which I linked above.

**Comment by euggersh** [comment]
Thanks for the link.  I must be missing something, but I'm not seeing how that documentation relates to the NUT add-on for Home Assistant.  Is there a configuration file somewhere that needs to be updated?  Apologies if I missed that explanation somewhere.

**Comment by sinclairpaul** [comment]
The config options <https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#sub-option-config> get placed into ups.conf.  The addon doesn't do anything special with the application, it just installs and formats the config files as required.

**Comment by euggersh** [comment]
I should have been more clear that by "same issue" I meant that the add-on immediately stops after starting, rather than being SNMP-related.

Thanks for the link to the configuration documentation... I did indeed miss it on the main repository page.  However, I'm still not clear on where ups.conf is supposed to be.  Does the add-on create it?  I don't see it anywhere in my Home Assistant folder tree.

**Comment by sinclairpaul** [comment]
Then please post your logs and config, UPS details, install details in a new issue.

Thanks 👍
