### ISSUE TITLE
No matching HID UPS found - Driver failed to start APC BACK-UPS ES (BE850G2)

### ISSUE THREAD

**Issue by cj-github** [hassio-addons/addon-nut#252]
# Problem/Motivation

> UPS installed on RaspberryPi with APC BACK-UPS ES (BE850G2) device.

ups.conf file is loaded with:

```
[ups]
        driver = usbhid-ups
        port = auto
        vendor = "American Power Conversion Uninterruptible Power Supply"
        vendorid = 051d
        productid = 0002
```

List here [https://networkupstools.org/stable-hcl.html](url) suggests using usbhid-ups driver, however trying to start shows no matching HID UPS and Driver fails.

```
sudo upsdrvctl start
Network UPS Tools - UPS driver controller 2.7.4
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
No matching HID UPS found
Driver failed to start (exit status=1)
```

lsusb shows:
```
Bus 001 Device 004: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
```

## Help

Am I loading in the correct driver? Is there any other way to troubleshoot this? 

Thanks for your help.

**Comment by Rgasd** [comment]
Hi,
i have the same device :Back-UPS ES 850G2
von American Power Conversion
Firmware: 938.a2 .I

and it´s running fine, even on latest
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.10.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true
  },


my addon-config is as simple as this in Frencks addon : 
- config: []
  driver: usbhid-ups
  name: apcups
  port: auto

hope this helps you, give it a try..

**Comment by Rgasd** [comment]
even more info here 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.0
 Home Assistant Supervisor: 2022.10.2
 
 cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[17:52:57] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[17:52:57] INFO: Setting mode to netserver...
[17:52:57] INFO: Connected USB devices:

Bus 001 Device 004: ID xxxxxx American Power Conversion Uninterruptible Power Supply

[17:52:57] INFO: Generating /etc/nut/upsd.users...

[17:52:59] INFO: Configuring Device named apcups...
[17:53:00] INFO: Starting the UPS drivers...
Using subdriver: APC HID 0.96
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 0
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun upsd (no readiness notification)
services-up: info: copying legacy longrun upsmon (no readiness notification)
s6-rc: info: service legacy-services successfully started
[17:53:01] INFO: Starting the UPS information server...
   0.000000	fopen /run/nut/upsd.pid: No such file or directory
   0.001307	listening on 0.0.0.0 port 3493
   0.002698	Connected to UPS [apcups]: usbhid-ups-apcups
[17:53:02] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000838	Using power down flag file /etc/killpower
   0.001231	UPS: apcups@localhost (master) (power value 1)
   0.001613	debug level is '1'
   0.001659	Warning: running as one big root process by request (upsmon -p)
   0.002415	Init SSL without certificate database
   0.007021	Trying to connect to UPS [apcups@localhost]
   0.536876	User upsmonmaster@127.0.0.1 logged into UPS [apcups]
   0.010473	Logged into UPS apcups@localhost
{"message":"Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
{"message":"Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4

**Comment by cj-github** [comment]
Thank you for getting back to me. It's good to know it can work!

I've tried your config, but it still doesn't work.

What did you mean?
> my addon-config is as simple as this in Frencks addon :

I'm not using home assistant - just the standard ups tools install.  What is the Frencks addon?

thanks

**Comment by sinclairpaul** [comment]
You have posted on the repo for the Home Assistant container that packages NUT, the NUT project itself can be found at https://github.com/networkupstools

**Comment by cj-github** [comment]
oh sorry - thanks
