### ISSUE TITLE
Feature Request - Enable TLS communications for the NUT addon

### ISSUE THREAD

**Issue by adub08** [hassio-addons/addon-nut#256]
# Problem/Motivation

NUT out of the box, and therefore this addon, does not encrypt the session between NUT and the clients which connect to it. The authentication is passed in cleartext. 
## Expected behaviour
The Ideal situation would be that any network clients connecting to NUT would use TLS for session authentication and encryption.

## Proposed changes

Add an option that re-builds NUT with OpenSSL support as described here [https://networkupstools.org/docs/user-manual.chunked/ar01s10.html#_configuring_ssl](url) or use a pre-built "NUT TLS shim" as described here which may easier to enable as described here: [https://github.com/networkupstools/TLS-Shims](url)

Just some (hopefully helpful) suggestions :smiley:

**Comment by frenck** [comment]
Best option is to use a proxy to handle that, this addon will not be updated to support this.

../Frenck
