### ISSUE TITLE
NUT crashes when modifying a sensor name, doesn't restart automatically

### ISSUE THREAD

**Issue by loryanstrant** [hassio-addons/addon-nut#257]
# Problem/Motivation

NUT keeps crashing but doesn't restart even though Watchdog is enabled.

## Expected behavior

Should restart automatically.

## Actual behavior

Doesn't restart.

## Steps to reproduce

Seems to occur when a sensor is manually updated (whether you actually change the name or just click it and press "Update" without changing anything).

Setup:
- HA OS 9.3 in a VM on a Synology DS920+
- Core 2022.11.2

## Proposed changes

Not sure of how to fix it. But here's a screenshot of it showing that it hasn't started, but should have.

![image](https://user-images.githubusercontent.com/51473494/204167651-47519728-7b9e-49c0-92aa-fdec9aa8e4e2.png)

**Comment by sinclairpaul** [comment]
Not sure on the reference to the sensor isn't that the integration?

Are there logs available from the addon stopping?

**Comment by loryanstrant** [comment]
What I mean, is that if I modify the name of this, it will crash:
![image](https://user-images.githubusercontent.com/51473494/204177100-be6c9494-51b9-430d-83d2-d886221d5b3a.png)

Unfortunately once it's crashed I can't get into the logs via the UI - only once it starts again.
Is there somewhere you could suggest that I look?

**Comment by loryanstrant** [comment]
Here's the current log, although when going in to get this I noticed that the add-on had crashed again (even though I hadn't touched anything):
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.1
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[14:35:46] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[14:35:47] INFO: Setting mode to netserver...
[14:35:47] INFO: Generating /etc/nut/upsd.users...
[14:35:49] INFO: Configuring user: admin
[14:35:49] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[14:35:50] INFO: Configuring Device named myups...
[14:35:53] INFO: Starting the UPS drivers...
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
No matching HID UPS found
Network UPS Tools - UPS driver controller 2.7.4
Driver failed to start (exit status=1)
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by loryanstrant** [comment]
Hrm, seems to have crashed again, without me touching it.

**Comment by loryanstrant** [comment]
I did notice that this was enabled for some reason.
Have just disabled it, will see how long it stays up for.
![image](https://user-images.githubusercontent.com/51473494/204189990-e0614e6f-0528-4970-9571-a54b8b52b7d2.png)

**Comment by sinclairpaul** [comment]
```
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
No matching HID UPS found
Network UPS Tools - UPS driver controller 2.7.4
```

The log you posted show the addon failing to start, as it cannot locate your UPS, please validate your configuration and connections.
