### ISSUE TITLE
Need to add maxretry option in the configuration

### ISSUE THREAD

**Issue by perebusquets** [hassio-addons/addon-nut#260]
# Problem/Motivation

Hi, first of all, thanks for this wonderful addon :)

I'm in the need of adding the option `maxretry` (usually added on top of `ups.conf`, outside of the "array" of devices). 
The need comes from having a to use the `dummy-ups` driver in repeater mode, but the problem arises on start, since the dummy driver tries to connect to the real ups (connected via `usbhid-ups`) before it's connected, making NUT stop all processes. To avoid this, the recommendation from them is to add the `maxretry` option in order to allow the real UPS to have time to connect while the dummy one retries.

Here you can see a post with a similar case to mine: https://serverfault.com/questions/655797/nut-ups-dummy-driver-in-repeater-mode-for-synology-nas

## Expected behavior

To have a way to configure `maxretry`.

## Actual behavior

Not having a way to configure `maxretry`.

## Steps to reproduce

Not applicable.

## Proposed changes

Add `maxretry` as an option.

**Comment by sinclairpaul** [comment]
Sorry this is such an edge case that we wouldn't add it, would suggest a fork or run the software elsewhere.

**Comment by perebusquets** [comment]
Aw that's too bad... In case you ever plan to add it please ping me, I'll probably be able to open PR (since I'll be forking this repo and adding it to the options). Thanks for the fast response anyway!
