### ISSUE TITLE
Expose port from addon

### ISSUE THREAD

**Issue by rlinq** [hassio-addons/addon-nut#261]
# Problem/Motivation

Have added a Tecnoware UPS EXA Plus 1500 as a local USB device and it works well and is recognized using the blazer_usb driver. 
The NUT integration is also configured against the local nut server. I expected this addon to also expose the port so other devices can use the UPS status info. 

In config.yml port 3493 is not configured to be exposed outside the container. 
https://github.com/hassio-addons/addon-nut/blob/aa440f8fcb7d17df0a40d76e3918827c1a7e3014/nut/config.yaml#L23

I tried workarounds to change the config.yml but as soon as hass is restarted the latest version of the addon is either pulled or checked out so my local changes are reverted.

## Expected behavior

I would like to have at least an option to expose the port for others to consume the nut server data.

## Actual behavior

Port 3493 is not reachable from the network where homeassistant is located

## Steps to reproduce

Configure nut server with an local USB UPS. Set username and password. Try to connect to the port on the homassistant IP. 

## Proposed changes

Change from
ports:
 https://github.com/hassio-addons/addon-nut/blob/aa440f8fcb7d17df0a40d76e3918827c1a7e3014/nut/config.yaml#L23
  
To 
  3493/tcp: 3493

**Comment by sinclairpaul** [comment]
There is, under the configuration network section, this is the same for all HomeAssistant addons.

**Comment by rlinq** [comment]
Thanks for fast comment and clarification. 
I have search and failed to find any documentation that would instruct what to configure. Do you possible have a link to a doc that outlines what to change to expose a port for this addon?

**Comment by sinclairpaul** [comment]
Scroll down on the configuration page, add the port you would like mapped:

![image](https://user-images.githubusercontent.com/24625998/209222940-7a35d791-5bf4-4f24-b070-b247c991b78d.png)

**Comment by rlinq** [comment]
Wow, that was really a hidden option. It worked, thanks!

For future reference, add a port number in the field, save and restart the addon. 

The text should be changed as there is no default port. I've been trying to change the port to the right.

_Add a port that will be exposed by the add-on._

![image](https://user-images.githubusercontent.com/32157341/209223514-ad1baec3-6ca2-4451-8474-b1351f8f8cad.png)

**Comment by sinclairpaul** [comment]
> The text should be changed as there is no default port. I've been trying to change the port to the right.

That's a feature of the Home Assistant UI, not anything that the addon itself can address.
