### ISSUE TITLE
NUT shutting down the host but the UPS does not shut power-off when FSD OB LB condition has been reached

### ISSUE THREAD

**Issue by wzmigrod** [hassio-addons/addon-nut#263]
I am running HA (HA OS) on a NUC type machine (HP Thin Client T630) and an EATON 3S 550 (first generation) UPS- typical standalone configuration
The NUT add-on and NUT integration in general works OK - UPS is visible, all UPS status data are displayed however I cannot get ups to shut down when the low battery condition has been reached

In short:

when on battery and when low battery condition has been reached NUT triggers Home Assistant shut down (FSD OB LB)
the power supply on ups outlets is still on until battery of the ups has been drained to 0

I can execute the clean shutdown of both T630 and UPS by executing following commands in the terminal window:

**docker exec addon_a0d7b954_nut upscmd -u user -p password myups@127.0.0.1 load.off.delay 90**
**shutdown**

The NUT add-on configuration is a follows

devices:
  - config:
      - default.ups.delay.shutdown = 70
      - default.ups.delay.start = 100
      - default.ups.beeper.status = enabled
      - default.battery.charge.low = 20
      - default.outlet.switchable = yes
    driver: usbhid-ups
    name: myups
    port: auto
mode: netserver
shutdown_host: true
users:
  - actions: []
    instcmds:
      - all
    password: xxxxxxxxx
    username: wzmigrod
list_usb_devices: true
pollonly: enabled
log_level: debug

I have been experimenting a bit with shut down & start delays - trying to figure out if that has any impact on the behaviour but see no difference

the NUT addon log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.12.9
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to DEBUG
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[20:15:23] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[20:15:23] INFO: Setting mode to netserver...
[20:15:23] INFO: Connected USB devices:
Bus 001 Device 004: ID 10c4:ea60 Silicon Labs CP210x UART Bridge
Bus 001 Device 003: ID 0463:ffff MGE UPS Systems UPS
Bus 001 Device 002: ID 0438:7900 Advanced Micro Devices, Inc. Root Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 004: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
Bus 002 Device 003: ID 093a:2510 Pixart Imaging, Inc. Optical Mouse
Bus 002 Device 002: ID 045e:07f8 Microsoft Corp. Wired Keyboard 600 (model 1576)
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[20:15:24] INFO: Generating /etc/nut/upsd.users...
[20:15:24] INFO: Configuring user: wzmigrod
[20:15:25] DEBUG: Password SHA1: FA23328B84762789E52F73E3C441D4845057E399
[20:15:25] DEBUG: Requested API resource: https://api.pwnedpasswords.com/range/FA233
[20:15:25] DEBUG: API HTTP Response code: 200
[20:15:25] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[20:15:27] INFO: Configuring Device named myups...
[20:15:28] INFO: Starting the UPS drivers...
   0.000000	Starting UPS: myups
Using subdriver: MGE HID 1.40
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
[20:15:33] WARNING: UPS Shutdown will shutdown the host
cont-init: info: /etc/cont-init.d/nut.sh exited 0
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun upsd (no readiness notification)
services-up: info: copying legacy longrun upsmon (no readiness notification)
s6-rc: info: service legacy-services successfully started
[20:15:33] INFO: Starting the UPS information server...
   0.000000	fopen /run/nut/upsd.pid: No such file or directory
   0.001026	listening on 0.0.0.0 port 3493
   0.001550	Connected to UPS [myups]: usbhid-ups-myups
[20:15:34] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000508	Using power down flag file /etc/killpower
   0.000850	UPS: myups@localhost (master) (power value 1)
   0.000973	debug level is '1'
   0.000996	Warning: running as one big root process by request (upsmon -p)
   0.001528	Init SSL without certificate database
   0.021551	Trying to connect to UPS [myups@localhost]
   0.482038	User upsmonmaster@127.0.0.1 logged into UPS [myups]
   0.024099	Logged into UPS myups@localhost

Looked into configuration files in the /etc/nut folder but do not see anything wrong that would be an obvious reason for UPS not shutting down (perhaps LISTEN 0.0.0.0 in upsd.conf looks a bit suspicious to me).
So it looks as if the add-on was not passing the right command to  the UPS to power-off

I have also tested the same UPS with a Windows machine and Windows dedicated Eaton UPS companion - in that configuration both Windows machine and the UPS shut down as expected.

[nut_conf.txt](https://github.com/hassio-addons/addon-nut/files/10339628/nut_conf.txt)
[shutdownhost.txt](https://github.com/hassio-addons/addon-nut/files/10339629/shutdownhost.txt)
[ups_conf.txt](https://github.com/hassio-addons/addon-nut/files/10339630/ups_conf.txt)
[upsd_users.txt](https://github.com/hassio-addons/addon-nut/files/10339631/upsd_users.txt)
[upsd_conf.txt](https://github.com/hassio-addons/addon-nut/files/10339632/upsd_conf.txt)
[upsmon_conf.txt](https://github.com/hassio-addons/addon-nut/files/10339633/upsmon_conf.txt)

**Comment by sinclairpaul** [comment]
The challenge with running NUT in a container is that with a usual install it uses the init process to know when the OS is shutdown.  There is no way of doing this, apart from "guessing" an amount of time for things to power down.

It also gets more challenging when there are multiple UPS devices and systems involved, so it's not likely something we can fix.

I doubt the default.something entries in your config are actually doing anything.

**Comment by wzmigrod** [comment]
So what's the solution? ( I mean for such a simple standalone system - guess that's the vast majority).
I can configure the T630 so that it shuts down and is does not start again until there as a certain break in power supply and then power supply is restored again so the timing is not that crucial. However I wan to avoid the situation that UPS is on when on battery until it drains the battery to 0

NB: regarding default entries - I started experimenting with those as I could see a way to fix the issue based on avaialbel configuration options. I can set the low batter threshold this way and it does have an effect (at least FSD + OB + LB) notification is generated properly; however enabling/disabling beeper does not

**Comment by sinclairpaul** [comment]
> So what's the solution? 

In all honesty, don't run NUT in a container, by design it won't be able to tell when the OS is finished shutting down and the container will have stopped prior to that.  Considering the majority of installs on SD cards, I'm not happy potentially force powering off devices based on a guess timer. 

You could always use the automation platform that you have running to send commands if needed.

**Comment by wzmigrod** [comment]
So, if I understand correctly, You suggest a solution with e.g. Proxmox installation with NUT running as server and Home Assistant with NUT add-on as client - right?

Anyway - I understood the drawbacks of running NUT in a container; however I believe in my case I could be set it up in such a way that that risk of having disk file system corrupt would be very small. I have configured T630 so the that it will not reboot until the power is off and on again. So is if the delay on powering the UPS off would be around 70- 90 seconds then it could be a safe solution. But I cannot find a way for the UPS to power-off

Regarding sending commands from automation platform - any hint ?(though of using the stdin service of SSH & web terminal but this solution is no longer available)

**Comment by wzmigrod** [comment]
Well, I solved my problem by installing Home Assistant under Proxmox; however perhaps it might make sense to update the documentation of the NUT addon so that others don't waste time on hopeless attempts
