### ISSUE TITLE
NUT fails to start

### ISSUE THREAD

**Issue by cableghost** [hassio-addons/addon-nut#265]
# Problem/Motivation
According to the Log, my UPS is unrecognized; NUT Log stating... "No matching HID UPS found".
My CP1350 is listed in the NUT Compat List
Note, at this point, I do not have the Integration installed as according to the directions, I need to have this add-on started first.

## Expected behavior
NUT starts and recognizes my UPS.

## Actual behavior
NUT starts, but soon stops

## Steps to reproduce
1) Install add-on
2) Enter config info
3) Reboot HA
4) Start NUT Add-on

I have read through several HA Community threads and have not seen a solution that works for me, assuming that this is all I need to do.

## Config
devices:
```
- config: []
  driver: usbhid-ups
  name: CP1350
  port: auto
```

users:
```
- actions: []
  instcmds:
    - all
  password: *****
  username: nut_scott
```

## Log
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.1
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[16:23:47] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[16:23:47] INFO: Setting mode to netserver...
[16:23:47] INFO: Generating /etc/nut/upsd.users...
[16:23:47] INFO: Configuring user: nut_scott
[16:23:47] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[16:23:48] INFO: Configuring Device named CP1350...
[16:23:48] INFO: Starting the UPS drivers...
No matching HID UPS found
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Driver failed to start (exit status=1)
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by sinclairpaul** [comment]
It can't see the device, make sure that HA can see it and you can use the option in the documentation to confirm <https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#option-list_usb_devices>

**Comment by cableghost** [comment]
Thank you for the quick reply.
Pardon my ignorance... I've only known to use the HA Integration process to connect devices, and there is no CyberPower Integration.
How do I then connect the UPS to HA?

**Comment by sinclairpaul** [comment]
That would mean that the supervisor cannot see the device, which would explain why the addon cannot see it (you should see something under Connected USB devices, it is running lsusb and outputting the info)

Check the cables, are you using a Hypervisor to run?, if so check the configuration there, it really isn't an issue with the addon, as the hardware isn't being passed through.

**Comment by cableghost** [comment]
Thank you. For others... My Hyper-V setup does not pass-through this USB connection automatically. Furthermore, I discovered I cannot have the UPS simultaneously, actively connected to host and my HA vm (HASS.IO) at the same time. Since I'm using CP PowerPanel on host, makes this a moot point.
