### ISSUE TITLE
Unable to save configuration of freshly installed Network UPS Tools

### ISSUE THREAD

**Issue by uvalkonovic** [hassio-addons/addon-nut#270]
Im unable to save configuration of freshly installed Network UPS Tools

Error message is:
Failed to save add-on configuration, Unknown error, see supervisor logs

Logs are:

Failed to to call /addons/a0d7b954_nut/options/validate -

Timeout on /addons/a0d7b954_nut/options/validate request

Trying to save username and password to configuration of NUT.

To reproduce Install NUT then fill in Username and Password to configuration then get this error.
No difference between editing from GUI or yaml.

No difference NUT running or stopped.

Cant start NUT with error

[17:02:13] FATAL: 
[17:02:13] FATAL: Setting a username is required!
[17:02:13] FATAL: 
[17:02:13] FATAL: Please username in the 'users[0].username' option.
[17:02:13] FATAL: 
[17:02:13] FATAL: If unsure, check the add-on manual for more information.
[17:02:13] FATAL: 

Network UPS Tools
Current version: 0.11.0

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

**Comment by sinclairpaul** [comment]
Please post your config, looks to be a formatting issue.

**Comment by uvalkonovic** [comment]
> Please post your config, looks to be a formatting issue.

Cant save edited config, config is fresh after installation...

**Comment by uvalkonovic** [comment]
> Please post your config, looks to be a formatting issue.

devices:
  - config: []
    driver: usbhid-ups
    name: myups
    port: auto
mode: netserver
shutdown_host: "false"
users:
  - actions: []
    instcmds:
      - all
    password: thjrwehjryejtje
    username: jketyjetyjtyjty

**Comment by uvalkonovic** [comment]
this is default config after installation

devices:
  - config: []
    driver: usbhid-ups
    name: myups
    port: auto
mode: netserver
shutdown_host: "false"
users:
  - actions: []
    instcmds:
      - all
    password: ""
    username: ""

**Comment by uvalkonovic** [comment]
So the resolution is, that it is not possible to save any config in HA which contains password in case, that HA is connected to the Internet and it is not available connection to IP 104.18.206.87:443.

And a second, when NUT is starting, it is also checking pwned database, when HA is disconnected from Internet,
NUT writes to startup log this:

curl: (6) Could not resolve host: api.pwnedpasswords.com
ERROR: Something went wrong contacting the HIBP API
WARNING: Could not check password, assuming it is safe.

And then it normally starts.

Could you be so kind and remove this functionality from NUT,
or add some switch to the config which turns off this functionality?

Thank you.

**Comment by sinclairpaul** [comment]
Please refer to the documentation <https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#option-i_like_to_be_pwned>
