### ISSUE TITLE
ERR ACCESS-DENIED due to 2FA needed for account login on remote UPS server

### ISSUE THREAD

**Issue by Cikkajes** [hassio-addons/addon-nut#272]
# Problem/Motivation
I have a Synology NAS connected via USB to a UPS. I have configured the NUT addon to access the UPS server setup on the NAS and all looks good until it says that the access is denied. I believe this is because I would need to input my 2FA.

> (Why the issue was filed)
Cannot run addon without log in on UPS server.

## Steps to reproduce
Setup Synology NAS as UPS server, allow port 3493 in NAS firewall. Configure NUT addon in netclient mode and fill in required fields. 

## Proposed changes
Add pop-up to insert 2FA to allow successful login.

**Comment by sinclairpaul** [comment]
Not really sure what you are trying to accomplish here, maybe you could post your config?.

In all honesty I don't understand the 2FA reference, which I am guessing is to your NAS management page.

**Comment by Cikkajes** [comment]
Yes, correct, the NAS has 2-factor authentication to login into it. The NAS has been set up as follows for the UPS: [https://www.smarthomebeginner.com/nut-sensor-on-home-assistant-synology-ups/](https://www.smarthomebeginner.com/nut-sensor-on-home-assistant-synology-ups/)

When trying to configure the add-on, it asks me for username and password in the config, but there is no way to input the 2FA code to complete the login process, thus it gives me access denied in the log.

Here's the config:

devices:
  - config: []
    driver: usbhid-ups
    name: myups
    port: auto
mode: netclient
shutdown_host: "false"
users:
  - actions: []
    instcmds:
      - all
    password: ""
    username: ""
remote_ups_host: 192.168.1.124:3493
remote_ups_user: 'username'
remote_ups_password: 'secret'
list_usb_devices: true
remote_ups_name: ups


the log stops with the following:
Login on UPS [ups@192.168.1.124:3493] failed - got [ERR ACCESS-DENIED]

**Comment by sinclairpaul** [comment]
```remote_ups_host: 192.168.1.124:3493``` I would suggest removing the port here

The 2FA for your Synology Management Interface won't be used by the NUT server, if removing the port doesn't work, I would suggest there is an issue in the account you configured (you have to specify which hosts are allowed to use the account when setting it up).

However as you have ```shutdown_host: "false"``` I don't understand why you want to install NUT as an addon running as a Netclient, you can configure the integration in Home Assistant to talk directly to your NUT install on your NAS.

**Comment by Cikkajes** [comment]
Thanks for the feedback.

I have other working addons on Home Assistant that talk to the NAS, and they ask me for the 2FA during configuration via a pop-up. 

Maybe explaining the setup can help. The UPS is connected via USB to the NAS, Home Assistant is currently in another room, so it needs to communicate with the NAS on the LAN to get the info on the UPS. The UPS powers the NAS, a switch and the modem router.
Home Assistant has its own dumb UPS which does not give info about its state but should last longer than the main UPS. 

I am still playing around and experimenting, but an idea I have is to automatically turn off Home Assistant if the NAS is being powered by its UPS for more than 15 minutes.

I tried removing the port, but it is still not working. The NAS has Home Assistant's IP as allowed to check in on the UPS state. My feeling is that I need to add the 2FA to successfully access the NAS from the NUT add-on, but there is no prompt to do so.

**Comment by sinclairpaul** [comment]
The 2FA auth is for your NAS admin interface not the NUT server.

It sounds to me what you actually want to configure is the Home Assistant Integration which is referenced in the document you linked and can be found at <https://www.home-assistant.io/integrations/nut/>

I'm closing this out, as this is configuration and not an issue with the addon.
