### ISSUE TITLE
The plugin does not start

### ISSUE THREAD

**Issue by joseones** [hassio-addons/addon-nut#273]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.3
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[13:29:35] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[13:29:35] INFO: Setting mode to netserver...
[13:29:36] INFO: Generating /etc/nut/upsd.users...
[13:29:36] INFO: Configuring user: jose
[13:29:37] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[13:29:38] INFO: Configuring Device named myups...
[13:29:38] INFO: Starting the UPS drivers...
No supported UPS detected
Network UPS Tools - Megatec/Q1 protocol USB driver 0.12 (2.7.4)
Driver failed to start (exit status=1)
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by thanpolas** [comment]
Getting the same error. Folder "/run/uncaught-logs/current" where the error log is supposed to be, doesn't exist unfortunately.

**Comment by thanpolas** [comment]
Never mind, this is a dup of #265

**Comment by NorDroN** [comment]
The same error :(

**Comment by joseones** [comment]
I have changed the "blaze_usb" driver for "nutdrv_qx" and it hasn't stopped for more than a week

**Comment by Patrick762** [comment]
Same error here

**Comment by NorDroN** [comment]
Any updates on this?
