### ISSUE TITLE
Cannot define an "upsmon slave" user

### ISSUE THREAD

**Issue by euidzero** [hassio-addons/addon-nut#275]
# Problem/Motivation

I try to connect to nut server on my HA from a nut-client elsewhere in the same network.

## Expected behavior

I should be able to define a NUT user with the mode "upsmon slave"

## Actual behavior

The configured NUT user is in the form : 
```
  [username]
  password = redacted
  instcmds =all
```

To be allowed to connect remotely to the HA nut-server, this should be : 
```
  [username]
  password = redacted
  instcmds =all
  upsmon slave
```
but no option is given to add the missing directive in the configuration of the addon.
## Steps to reproduce

install the addon
configure in netserver mode
login into the addon container and check upsd.users

when trying to connect from a remote nut-client we get :
ERR ACCESS-DENIED

## Proposed changes

In nut-server mode allow to setup the "upsmon" mode to the configured users.

**Comment by sinclairpaul** [comment]
Please refer to the documentation <https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#sub-option-upsmon>
