### ISSUE TITLE
Cannot connect to server..

### ISSUE THREAD

**Issue by swordfish7x** [hassio-addons/addon-nut#276]
# Problem/Motivation

> (I used host name provided here, user and complex password, port 3493..)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.2.5
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[22:57:37] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[22:57:37] INFO: Setting mode to netserver...
[22:57:37] INFO: Generating /etc/nut/upsd.users...
[22:57:37] INFO: Configuring user: johndoe
[22:57:37] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[22:57:38] INFO: Configuring Device named myups...
[22:57:38] INFO: Starting the UPS drivers...
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
No matching HID UPS found
Driver failed to start (exit status=1)
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
```USB communication driver 0.33
No matching HID UPS found
Driver failed to start (exit status=1)
Network UPS Tools - UPS driver controller 2.7.4
```
The addon isn't starting as it is failing to find your UPS, make sure it is available and supported by the driver you are using.

**Comment by swordfish7x** [comment]
Hi, thank you for quick response.
This is how I manage to make it work.
My ups is Mustek 1000usb.


“It’s nice to be important but it’s more important to be nice!"
***@***.***

**Comment by sinclairpaul** [comment]
Not really sure what you mean, however looking at the documentation <https://networkupstools.org/stable-hcl.html> I believe your UPS probably uses the blazer_ups driver.  You can check the documentation <https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md#sub-option-driver> on how to change this.

As this isn't an addon issue, rather config, I will close this out.
