### ISSUE TITLE
Nut Add-On Exiting when started

### ISSUE THREAD

**Issue by Brianr1028** [hassio-addons/addon-nut#278]
Hello,

Starting today I noticed the HA add on for NUT was crashing immediately. I tested this on a back up HA system running on vmware and running a slightly dated version of HA. Then I tried a brand new install and immediately the NUT add on crashed again. Not sure how I can access the logs its referencing in the error below. Suggestions much appreciated.
Please, share the above information when looking for help
or support in, e.g., GitHub, forums or the Discord chat.

cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to INFO
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[01:20:20] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[01:20:20] INFO: Setting mode to netserver…
[01:20:20] INFO: Generating /etc/nut/upsd.users…
[01:20:20] INFO: Configuring user: admin
[01:20:20] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[01:20:21] INFO: Configuring Device named CyberPower 1325va…
[01:20:21] INFO: Starting the UPS drivers…
Error: no UPS definitions found in ups.conf
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by sinclairpaul** [comment]
```
Error: no UPS definitions found in ups.conf
```

This points to an issue with your config as the addon is failing to start

**Comment by Brianr1028** [comment]
thanks for offering to help. This same config worked as recently as this past Saturday. 

devices:
  - name: CyberPower 1325va
    driver: usbhid-ups
    port: /devices/pci0000:00/0000:00:14.0/usb1/1-2
    config:
      - vendorid = 0764
      - desc = CyberPower 1325va UPS
      - pollinterval = 15
mode: netserver
shutdown_host: false
users:
  - username: admin
    password: Cooper2023!
    instcmds:
      - all
    actions: []
list_usb_device: true
upsd_maxage: 60
upsmon_deadtime: 25
log_level: info

Suggestions, ideas welcome. BTW - If I set back to default I still get :

s6-rc: info: service s6rc-oneshot-runner successfully stopped

I am also seeing this on a brand new install of HA

**Comment by sinclairpaul** [comment]
I would change the port to auto as you only have one device and it should find it, I also doubt you need the vendorID.

I don't fully recall but it may be worth removing the spaces from the name field as well.

The error you are seeing is due to the data that we parse and place into the ups.conf file isn't in the format that NUT is expecting.  If it worked previously, what changed to cause this I really have no idea.

**Comment by Brianr1028** [comment]
I think I might be in business. The only thing I did on Saturday was setup another UPS, one not attached to the thin client desktop and the integration seemed to work. But I have had some issues with this new Orange Pi and was testing it out. 

I did as you suggested. I think I am business, but not sure. 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.3.1
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to INFO
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[19:49:19] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/nut.sh
[19:49:19] INFO: Setting mode to netserver...
[19:49:19] INFO: Generating /etc/nut/upsd.users...
[19:49:19] INFO: Configuring user: admin
[19:49:19] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[19:49:20] INFO: Configuring Device named CyberPower1325va...
[19:49:20] INFO: Starting the UPS drivers...
Using subdriver: CyberPower HID 0.4
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 0
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun upsd (no readiness notification)
services-up: info: copying legacy longrun upsmon (no readiness notification)
s6-rc: info: service legacy-services successfully started
[19:49:20] INFO: Starting the UPS information server...
   0.000000	fopen /run/nut/upsd.pid: No such file or directory
   0.000343	listening on 0.0.0.0 port 3493
   0.000680	Connected to UPS [CyberPower1325va]: usbhid-ups-CyberPower1325va
[19:49:21] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000372	Using power down flag file /etc/killpower
   0.000634	UPS: CyberPower1325va@localhost (master) (power value 1)
   0.000729	debug level is '1'
   0.000761	Warning: running as one big root process by request (upsmon -p)
   0.001167	Init SSL without certificate database
   0.017477	Trying to connect to UPS [CyberPower1325va@localhost]
   0.530355	User upsmonmaster@127.0.0.1 logged into UPS [CyberPower1325va]
   0.020035	Logged into UPS CyberPower1325va@localhost

**Comment by sinclairpaul** [comment]
Those logs show the addon as running, glad you got it resolved, will close this out.
