### ISSUE TITLE
NUT Check in frequency

### ISSUE THREAD

**Issue by Brianr1028** [hassio-addons/addon-nut#280]
Hello,

I am running NUT add-on on a thin client desktop. One of my UPS's is connected to the thin client desktop. What I have noticed is some of the available fields that are available when I add the integration do not seem to check in for long periods of time. I understand if something is not active and not communicating with NUT then why communicate. But I would at least want the check ins to occur at least a few times a day. What I seem to be observing is that the inactive fields only seem to check in with HA if the console is restarted. Is there way to increase the check in frequency? Current configuration shown below. Thanks.

devices:

name: CyberPower 1325va
driver: usbhid-ups
port: /devices/pci0000:00/0000:00:14.0/usb1/1-2
config:
vendorid = 0764
desc = CyberPower 1325va UPS
pollinterval = 15
mode: netserver
shutdown_host: false
users:
username: admin
password: mypassword
instcmds:
all
actions: []
list_usb_device: true
upsd_maxage: 60
upsmon_deadtime: 25
log_level: info

**Comment by sinclairpaul** [comment]
This would be related to the integration, not the addon.  There isn't anything that can be done for it here, and would need to be raised on the HA repo.
