### ISSUE TITLE
The plugin does not start after upgrade to OS 10.0 - Error: Out of memory

### ISSUE THREAD

**Issue by robercy** [hassio-addons/addon-nut#288]
# Problem/Motivation

The plugin does not start after upgrade to OS 10.0 - Error: Out of memory

Add-on: Network UPS Tools
Manage battery backup (UPS) devices
Add-on version: 0.11.1
You are running the latest version of this add-on.
System: Home Assistant OS 10.0.rc1  (running Generic x86-64 under Proxmox)
Home Assistant Core: 2023.3.6
Home Assistant Supervisor: 2023.03.2

## Actual behavior
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nut.sh
[09:20:54] INFO: Setting mode to netserver...
[09:20:54] INFO: Connected USB devices:
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 003: ID 0bda:8771 Realtek Semiconductor Corp. Bluetooth Radio
Bus 002 Device 002: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd QEMU USB Tablet
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
[09:20:54] INFO: Generating /etc/nut/upsd.users...
[09:20:54] INFO: Configuring user: admin
[09:20:54] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[09:20:54] INFO: Configuring Device named myups...
[09:20:54] INFO: Starting the UPS drivers...
Using subdriver: APC HID 0.96
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 0
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun upsd (no readiness notification)
services-up: info: copying legacy longrun upsmon (no readiness notification)
s6-rc: info: service legacy-services successfully started
[09:20:55] INFO: Starting the UPS information server...
   0.000000	fopen /run/nut/upsd.pid: No such file or directory
   0.000329	listening on 0.0.0.0 port 3493
   0.000629	Connected to UPS [myups]: usbhid-ups-myups
   0.000679	Out of memory: Cannot allocate memory   <================================ ERROR
Network UPS Tools upsd 2.7.4
[09:20:55] WARNING: upsd crashed, halting add-on
s6-rc: info: service legacy-services: stopping
[09:20:55] INFO: upsd stopped, restarting...
[09:20:55] INFO: upsmon stopped, restarting...
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stop

**Comment by frenck** [comment]
Not an issue with the add-on, but an issue with the Home Assistant Operating System. Please report the issue with that project.

../Frenck
