### ISSUE TITLE
Poll UPS failed - Data stale

### ISSUE THREAD

**Issue by rendas** [hassio-addons/addon-nut#29]
# Problem/Motivation
NUT stops working after around 4 days.
When this happens, all related entities in Home Assistant become Unknown.

## Expected behavior
Since the UPS is stable (it was not shutdown and has been working all the time), NUT should be working.

## Actual behavior
Everytime I start NUT, after around 4 or 5 days, it hangs somehow and in the logs, it can  be seen:
62165.284809	Poll UPS [myups@localhost] failed - Data stale
62170.285543	Poll UPS [myups@localhost] failed - Data stale
62175.286346	Poll UPS [myups@localhost] failed - Data stale
62180.287097	Poll UPS [myups@localhost] failed - Data stale
62185.287891	Poll UPS [myups@localhost] failed - Data stale
62190.288624	Poll UPS [myups@localhost] failed - Data stale
When this happens, all related entities in Home Assistant become Unknown.

## Steps to reproduce
I have been using EDGE repo, NUT version 5715820, HA 0.106.5, HassOS 3.11, Supervisor 208.
The same happened in previous versions of HA/HassOS.
My addon configuration:
"
users:
  - username: myupsuser
    password: myupsrandompassword
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: [] #I was using before pollfreq = 5
mode: netserver
shutdown_host: 'false'
shutdown_hassio: 'false'
i_like_to_be_pwned: 'false'
list_usb_devices: 'true'
"

## Proposed changes
If there no code issue is found, maybe a new parameter for restarting NUT can be created, to restart itself after a couple of days.

**Comment by sinclairpaul** [comment]
Please check #14 #15 in case they are related.

We would not add an automatic restart to the addon.

**Comment by MartyTremblay** [comment]
I looked at #14 and #15 with no luck. I wonder if this could help?
https://raspberrypi.stackexchange.com/questions/66611/nut-cyberpower-data-stale

**Comment by sinclairpaul** [comment]
You can set MAXAGE in the config, please also see https://github.com/hassio-addons/addon-nut#option-fake_usb_devices if it is relevant.

**Comment by lex-us345** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.1.1
 You are running the latest version of this add-on.
 System: HassOS 3.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.107.5
 Home Assistant Supervisor: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to ERROR
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
Network UPS Tools - UPS driver controller 3.8.0-3396-gcdc7c4b5b1
Network UPS Tools - Megatec/Q1 protocol USB driver 0.12 (3.8.0-3396-gcdc7c4b5b1)
Startup timer elapsed, continuing...
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by pmitev** [comment]
I am experiencing similar (perhaps the same problem). I have everything perfectly running (nut server with 2 clients), but after several days the build-in Synology NAS client complains that has lost connection to the server - the error message reported in the first post look familiar. Restarting the plugin fixes the problem... for several days... The second client is just a crontab task that pools the server that I made sure does not complain if the connection is lost.

**Comment by sinclairpaul** [comment]
Closing, I have seen the issue but seems to be resolved by the upsd_maxage parameter, for example:

```upsd_maxage: 25```
