### ISSUE TITLE
NUT not starting - Driver failed to start (exit status=1)

### ISSUE THREAD

**Issue by UPS90** [hassio-addons/addon-nut#294]
# Problem/Motivation
I'm Running on a HomeAssistant OS on a odroid n2+,  after installing the NUT Add-on it wont start.
There are 2 APC UPS connected to the Home assistant.

I get this output logging: 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nut.sh
[21:25:02] INFO: Setting mode to netserver...
[21:25:02] INFO: Connected USB devices:
Bus 002 Device 002: ID 05e3:0620 Genesys Logic, Inc. USB3.1 Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 051d:0003 American Power Conversion UPS
Bus 001 Device 003: ID 051d:0003 American Power Conversion UPS
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[21:25:02] INFO: Generating /etc/nut/upsd.users...
[21:25:02] INFO: Configuring user: Nups
[21:25:03] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[21:25:03] INFO: Configuring Device named myups...
[21:25:04] INFO: Starting the UPS drivers...
interrupt pipe disabled (add 'pollonly' flag to 'ups.conf' to get rid of this message)
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
No matching HID UPS found
Driver failed to start (exit status=1)
Network UPS Tools - UPS driver controller 2.7.4
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

## Expected behavior

Starting up the application without error

## Actual behavior

The application stops running

## Steps to reproduce

This is the config: 

users:
  - username: Nups
    password: ajeto5637
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: false
list_usb_devices: true

 Home Assistant 2023.4.6 
Supervisor 2023.04.1 
Operating System 10.0 
Frontend-versie: 20230411.1 - latest 

## Proposed changes

After some searching around it looks like a permission problem but i don't know how to fix it.

**Comment by sinclairpaul** [comment]
This is a configuration issue, please ensure you UPS devices are supported and configured correctly (you have for example only specified a single device, where you state you have multiple).

Closing as this isn't an addon issue, I would suggest you seek help on the forums or Discord for the correct configuration.
