### ISSUE TITLE
freezing while running

### ISSUE THREAD

**Issue by FilipCZE** [hassio-addons/addon-nut#297]
Hi,

I have installed fresh supervisor at my Pi. I was using the NUT server on my old installation without issues.

Now the addon starts OK, integration can found the APC, but after while the Addon stops sending data and it seems to be disconnected from the addon, but the addon is still running...

Not a APC issue, I tried to connect it into the Synology NAS and it works fine few days long.

**Comment by monsieurlatte** [comment]
I am having the same issue with a APC back ups 850.  What's weird is that even when it stops sending data when I restart the service it shows the APC in the USB list but in the logs it says Product is NULL so it is not possible to determine whether to activate max_report_size workaround.
