### ISSUE TITLE
Not Available in hassio-addons/repository

### ISSUE THREAD

**Issue by JohnnyPicnic** [hassio-addons/addon-nut#3]
Is there a  reason this addon is not available in hassio-addons/repository?
I was using the version from https://github.com/colindunn/hassio-addons but now see this version is being updated but it's not in the repo.
I installed it locally and it's working.

<blockquote><img src="https://avatars3.githubusercontent.com/u/814070?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/colindunn/hassio-addons">colindunn/hassio-addons</a></strong></div><div>Hass.io Addons. Contribute to colindunn/hassio-addons development by creating an account on GitHub.</div></blockquote>

**Comment by tjorim** [comment]
https://github.com/hassio-addons/repository/issues/113
