### ISSUE TITLE
Update to Dabian 12 an NUT 2.8

### ISSUE THREAD

**Issue by jkey** [hassio-addons/addon-nut#301]
# Problem/Motivation

I would like to propose updating the system to Debian 12, which would also include an update to NUT version 2.8. This update is important because it brings support for various devices that were previously not compatible with the current version.

## Expected behavior

After the update to Debian 12 and NUT 2.8, I expect the system to have improved compatibility with a wider range of UPS devices. This will enable users to connect and monitor their UPS devices that were previously unsupported. See #283 #226 #225

## Actual behavior

Currently, certain UPS devices are not recognised or supported by the existing Debian and NUT releases. This limitation prevents users from using these devices with the system and from accessing important UPS monitoring and management features.

## Steps to reproduce

1. Install the latest version of the Network UPS Tools add-on to the Home Assistant.
2. Attempt to connect and configure a UPS device that is known to be unsupported by the current version of the add-on.
3. Verify that the device is not recognised and cannot be used for UPS monitoring or management within Home Assistant.

## Proposed changes

I propose to update NUT to 2.8, which will provide improved compatibility and support for a wider range of UPS devices. This update will address the above limitations and allow Home Assistant users to seamlessly integrate their UPS devices into their smart home setup. By upgrading to NUT 2.8, users will benefit from improved support for newer UPS devices, enabling seamless integration and ensuring reliable power backup for their Home Assistant system.

**Comment by sinclairpaul** [comment]
It was released yesterday, it requires more than just updating the image here, but work around the base images and the relevant testing.

Closing for now, it will be done once the other work is complete.
