### ISSUE TITLE
Wrong sensors values (battery charge, battery runtime, ...)

### ISSUE THREAD

**Issue by jymorel** [hassio-addons/addon-nut#309]
Hi,
My configuration : HAOS on RPI4. UPS Eaton Ellipse Eco 650 on usb port of the RPI4. NUT add-on and integration in server mode.
My issue is that there are incorrect values for sensors « battery charge », « Battery runtime », « Current real power »  (42W instead of 26W), … 
For example, estimated battery runtime is 36 minutes, but UPS shutdown occurs after 2h30… 
![onduleur](https://github.com/hassio-addons/addon-nut/assets/96637729/3c63120f-eac1-4482-bb1d-5b57d017654a)

And I didn’t find any way to set or change the default values in the add-on settings and no possibility to change anything in the integration (no configuration file). Can anyone help me? Or is there no possibility because limitation due to HAOS ? 
Thank you

**Comment by frenck** [comment]
I think you misunderstand the difference between integrations and add-ons.

This is the add-on repository, however, you are reporting an Home Assistant integration issue.

There is nothing I can do about that from an add-on perspective.


../Frenck

**Comment by jymorel** [comment]
Ok I understand that my question is not clear and that maybe I am not at the right place…
So I Rephrase it. I would like to know if it is possible in the configuration add-on to set options that would allow to change variables values of the integration sensors (I didn’t find any way in the integration to do this …).
Fo example, in the add-on documentation (https://github.com/hassio-addons/addon-nut/blob/main/nut/DOCS.md) : 
"Option : users
Sub-option : actions
A list of actions that a user is allowed to perform. Valid actions are:
•	set: change the value of certain variables in the UPS."
But how to use « set » to change the values and which  variables ???
Sorry, but I don’t understand what I can do …

**Comment by frenck** [comment]
> change variables values of the integration sensors

This is not the integration.

../Frenck
