### ISSUE TITLE
FR > Option to do either automation/script when UPS is in low battery

### ISSUE THREAD

**Issue by remlei** [hassio-addons/addon-nut#315]
as the titles says, is there any way to run automation/script when low batter.

the shutdown_host make sense if you run the HA baremetal, but if your running HA on a hypervisor or vm or something, that's where the issue pops in. It only shuts down the HA guest VM but the host is not. 

if this addon let me have a option to run automation or script instead of shutdown_host, that is much better since I can use the SSH Command integration to send a shutdown command to the host via automation or script.

**Comment by sinclairpaul** [comment]
The addon fires HA events you can watch for, details are in the documentation.  As it is a container there is no way to influence the underlying OS.

**Comment by remlei** [comment]
oops I see... didnt see that one.

since im not really familiar with events and there's no examples for it here other than notification I asked around people and ended up with this automation based on notify type.

`alias: UPS Automation
description: ""
trigger:
  - platform: event
    event_type: nut.ups_event
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.notify_type == 'ONLINE' }}"
        sequence:
          - service: notify.notify
            data:
              message: UPS Mains Power Restored
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.notify_type == 'ONBATT' }}"
        sequence:
          - service: notify.notify
            data:
              message: UPS On-Battery
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.notify_type == 'LOWBATT' }}"
        sequence:
          - service: notify.notify
            data:
              message: UPS Low Battery, shutting down....
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - service: button.press
            data: {}
            target:
              entity_id: button.node_proxmox_shutdown
mode: single
`
