### ISSUE TITLE
APC PDU powerman-pdu Driver

### ISSUE THREAD

**Issue by andreaconfa** [hassio-addons/addon-nut#319]
# Problem/Motivation

> Hi, i'm setting up my rack PDU using NUT. I saw in the online NUT documentation thath there is an experimental driver called "powerman-pdu" that should make the job done.
Unfortunately this driver is not contained (i think) in this NUT addon.
Here the log output:

`[20:56:22] INFO: Configuring Device named PDU1_RACK...
[20:56:22] INFO: Starting the UPS drivers...
Network UPS Tools - UPS driver controller 2.8.0
Can't start /lib/nut/powerman-pdu: No such file or directory
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by sinclairpaul** [comment]
From looking at the documentation, it isn't built by default, so requires a custom build.  The addon installs NUT via the Debian sources, so it isn't something that would likely get implemented.

If you require this functionality, this addon likely isn't for you.
