### ISSUE TITLE
The HOST is rebooted after the add-on is launched

### ISSUE THREAD

**Issue by Onizyka** [hassio-addons/addon-nut#330]
# Problem/Motivation
The HOST is rebooted after the add-on is launched

## Actual behavior
Reboots the host completely.

## Steps to reproduce
Core 2023.11.1
Supervisor 2023.11.0
Operating System 11.1
UPS: APC-UPS Back CS 600
config: 
users:
  - username: Onizyka
    password: ********
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: "false"

![Изображение WhatsApp 2023-11-09 в 01 34 06_3619a916](https://github.com/hassio-addons/addon-nut/assets/63815254/86f00fd8-05bf-4f87-badf-46fe01d4839f)

After that, reboot the host.

Host is Intel NUC.

**Comment by sinclairpaul** [comment]
There is nothing in your log that shows that the addon rebooted the host, perhaps you could check your HA logs?

**Comment by Onizyka** [comment]
no logs... disconnecting is like turning off the power.

**Comment by Onizyka** [comment]
https://github.com/hassio-addons/addon-nut/assets/63815254/d0e956a4-ae2b-4047-a711-9be31e55f519

**Comment by sinclairpaul** [comment]
Then it's likely a hardware issue, possibly with your UPS, I would suggest troubleshooting it outside of Home Assistant, there is nothing that can be done from the Addon.

**Comment by Onizyka** [comment]
The UPS is not connected.

**Comment by Onizyka** [comment]
The problem is with the connected UPS, which is not connected.


There are no problems running this add-on on another server. 
Can be used with Intel NUC 
processor: Intel(R) Atom(TM) CPU E3815 @ 1.46GHz ?

**Comment by sinclairpaul** [comment]
By specifying the port as auto, NUT will scan to try and find a UPS, in doing so it looks like it is causing you a hardware issue.  I would suggest finding out what that hardware is (i.e. disconnect all USB devices)., or specify the port to use or vendor id etc.

**Comment by Onizyka** [comment]
I tried it like this
![Screenshot_1](https://github.com/hassio-addons/addon-nut/assets/63815254/7cd6d9e1-2f5a-4a2a-be47-80b6eabfb8c5)

**Comment by Onizyka** [comment]
shutdown_host: true, shutdown_host: false, shutdown_host: 'false', shutdown_host: "false"

**Comment by sinclairpaul** [comment]
> shutdown_host: true, shutdown_host: false, shutdown_host: 'false', shutdown_host: "false"

It isn't this causing your problem, as the addon would start successfully and then issue a message, it should be left at the default which is `shutdown_host: false`

Again something is causing a hardware issue when the port is at auto, which unfortunately I cannot help with troubleshooting.
