### ISSUE TITLE
NUT fails to start using SNMP.

### ISSUE THREAD

**Issue by MaxDucy** [hassio-addons/addon-nut#331]
# Problem/Motivation

NUT fails to start.

## Expected behavior
NUT started and working

## Actual behavior

Fails to start 

## Steps to reproduce
My devices configs:

```
devices:
  - name: UPS
    driver: snmp-ups
    port: 10.10.10.198
    config:
      - snmp_version = v1
mode: netserver
shutdown_host: "false"
```

Log:
```
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[11:17:06] INFO: Configuring timezone (Asia/Bangkok)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nut.sh
[11:17:06] INFO: Setting mode to netserver...
[11:17:06] INFO: Generating /etc/nut/upsd.users...
[11:17:06] INFO: Configuring user: lpn_admin
[11:17:06] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[11:17:07] INFO: Configuring Device named UPS...
[11:17:07] INFO: Starting the UPS drivers...
Created directory: /var/lib/snmp/cert_indexes
Startup timer elapsed, continuing...
Network UPS Tools - UPS driver controller 2.8.0
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by aquette** [comment]
hi @MaxDucy,

is your UPS reachable with SNMP v1 and the default "public" community (implied when not setting "config->community=xxx")?
also, additional info on the unit may be usefull (brand, model, ...)

**Comment by lightingman117** [comment]
Something is going on with an update [I just updated everything to latest].

I'll have to try to debug some and rollback changes to figure out which update it was.

`2023-12-18 10:40:59.982 DEBUG (SyncWorker_8) [homeassistant.components.nut] Error getting NUT vars for host a0d7b954-nut: Socket error.
2023-12-18 10:41:01.506 DEBUG (MainThread) [pynut2.nut2] NUT Class initialization, Host/Port: a0d7b954-nut:3493, Login: admin/sitec3!@
2023-12-18 10:41:01.506 DEBUG (SyncWorker_12) [pynut2.nut2] NUT2 requesting list_vars from server a0d7b954-nut
2023-12-18 10:41:03.054 DEBUG (SyncWorker_12) [homeassistant.components.nut] Error getting NUT vars for host a0d7b954-nut: Socket error.
2023-12-18 10:41:03.055 DEBUG (MainThread) [homeassistant.components.nut] Finished fetching NUT resource status data in 1.548 seconds (success: False)
2023-12-18 10:41:03.680 DEBUG (MainThread) [pynut2.nut2] NUT Class deleted, trying to disconnect.
2023-12-18 10:41:03.680 DEBUG (MainThread) [pynut2.nut2] NUT Class deleted, trying to disconnect.`

**Comment by sinclairpaul** [comment]
> Something is going on with an update [I just updated everything to latest].

This log shows the integration unable to connect to the NUT instance, not sure how this is related to the original issue logged.  If there is an issue with the addon please post it's logs and config in a different issue.

**Comment by lightingman117** [comment]
Ahh, my apologies. You are right it is not really related.

I felt they are interrelated as both quit working at the same time and it was useful information.

I talked to NUT dev a few months back and he/she admitted the SNMP class needs re-writing.

I haven't had time to help with diagnostics.

I'll do more investigations.

Thanks.

**Comment by lightingman117** [comment]
Rolling back NUT-addon to 0.12.0 still fails
Rolling back Core to 2023.9.0 still fails

```
Home Assistant 2023.9.0
Supervisor 2023.11.6
Operating System 11.2
Frontend 20230906.1 - latest
```

**Comment by alexandrechoske** [comment]
Im having the same problem also :/

Was working fine until some weeks ago.

![image](https://github.com/hassio-addons/addon-nut/assets/47279355/0cb3fb68-cab8-4ff6-b15a-e43e629c3c7c)
![image](https://github.com/hassio-addons/addon-nut/assets/47279355/037d5ed0-33c4-4ed0-af5b-17161a223262)
