### ISSUE TITLE
Missing MIB

### ISSUE THREAD

**Issue by masterx1981** [hassio-addons/addon-nut#334]
# Problem/Motivation

Missing mib for riello netman 102 plus network card firmware 1.21, using the snmp-ups driver i get in the logs:
`No matching MIB found for sysOID '.1.3.6.1.4.1.5491.6'!
Please report it to NUT developers, with an 'upsc' output for your device.
Going back to the classic MIB detection method.`
I have the mib files, but not know how integrate them in nut.

**Comment by sinclairpaul** [comment]
The addon wraps the current stable release, please investigate upstream.

**Comment by aquette** [comment]
@masterx1981 just to confirm that NUT doesn't yet support this unit (sysOID .1.3.6.1.4.1.5491.6).
As mentioned, please post a ticket https://github.com/networkupstools/nut/issues
mentioning this ".1.3.6.1.4.1.5491.6" sysOID, and providing the .MIB file for it, along with a snmpwalk dump.
NUT Community will be able to help you ;)

**Comment by masterx1981** [comment]
> @masterx1981 just to confirm that NUT doesn't yet support this unit (sysOID .1.3.6.1.4.1.5491.6). As mentioned, please post a ticket https://github.com/networkupstools/nut/issues mentioning this ".1.3.6.1.4.1.5491.6" sysOID, and providing the .MIB file for it, along with a snmpwalk dump. NUT Community will be able to help you ;)

Hi! Thanks for the help, i've opene the issue, but i not know how launch the snmps walk command, as isn't recognized on the ha installation...

**Comment by masterx1981** [comment]
Hi! I've analyzed a bit the snmp walk log, and i see 2 different sysoid. One is the unknown one, the other is OID=.1.3.6.1.2.1.33, that seem a standard ietf oid. And the status of the ups (voltage, frequency, etc) seem that are under this oid. But why aren't read by the nut service?
[Log (11).txt](https://github.com/hassio-addons/addon-nut/files/13607695/Log.11.txt)
