### ISSUE TITLE
Scan interval still not work

### ISSUE THREAD

**Issue by sblantipodi** [hassio-addons/addon-nut#34]
# Problem/Motivation

Scan interval does not work.

## Expected behavior

> sensor:
>   - platform: nut
>     scan_interval: 5
>     name: "CyberPower PR1500ELCD"
>     host: a0d7b954-nut #EDGE
>     username: user
>     password: !secret nut
>     resources:
> 

this should update the readings every 5 seconds

**Comment by frenck** [comment]
This is the add-on, your report is about an integration.
Please report things on the right places, your issue is with Home Assistant, not the add-on.

**Comment by sblantipodi** [comment]
thanks for the answer, I will try to open next issues in the right place, in the mean time you should consider this :)
https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

**Comment by sinclairpaul** [comment]
Issue doesn't need to be transferred:

https://github.com/home-assistant/core/pull/31167

https://rc.home-assistant.io/blog/2020/03/27/release-108/

**Comment by frenck** [comment]
@sblantipodi Next time you want to be a wise guy, read the page yourself before you throw it at me to teach me a lesson.

> You can only transfer issues between repositories owned by the same user or organization account.

This is a different organization.

Thanks.
