### ISSUE TITLE
Not powering down the UPS

### ISSUE THREAD

**Issue by abhi23768** [hassio-addons/addon-nut#35]
# Problem/Motivation
On Low Battery (LOWBATT), addon does not shut down UPS. 

## Expected behavior

When UPS battery get low, addon-nut should turn off UPS load (FSD) so that all devices that are attached to it are forcibly rebooted. The master should command the UPS into
the “forced shutdown” mode.

## Actual behavior
1. On Low battery, I get LOWBATT notification.
2.  It is followed by SHUTDOWN notification - Auto logout and shutdown proceeding.
The Home assistant gets shutdown but UPS continues and does not shutdown.
 

## Steps to reproduce

1. Switch the mains Power to UPS (ONBATT)
2. Wait for Low battery condition (LOWBATT)
Below is the configuration file : 
users:
  - username: '!secret nut_u'
    password: '!secret nut_p'
    upsmon: master
    instcmds:
      - all
    actions:
      - set
      - fsd
devices:
  - name: cyberups
    driver: usbhid-ups
    port: auto
    config:
      - lowbatt=15
      - offdelay=180
      - ondelay=0
mode: netserver
shutdown_host: 'true'
log_level: debug

## Proposed changes
As part of the shutdown, the addon should shutdown UPS -  to power off the load.
FSD "UPS %s: Forced shutdown in progress."

**Comment by sinclairpaul** [comment]
Can you give some details on where you get this behavior from?  The addon stops when asked to by NUT itself.

**Comment by sinclairpaul** [comment]
Also you may want to verify in the events that your UPS issues the OP LB event, https://networkupstools.org/docs/user-manual.chunked/ar01s06.html , as it should occur prior to the shutdown,

**Comment by abhi23768** [comment]
It seems OB LB was issued by the UPS, 
First I got the notification: UPS cyberups@localhost battery is low
Immediately after that, the second notification was: Auto logout and shutdown proceeding

6.3. Configuring automatic shutdowns for low battery events
In Shutdown design, Step 6 is getting executed (upsmon master calls the SHUTDOWNCMD as Home Assistant is getting Shutdown/halt) bur Step 8 (below) is not getting executed
_8. init then runs your shutdown script. This checks for the POWERDOWNFLAG, finds it, and tells the UPS driver(s) to power off the load.__

The issue is that If the mains power come back before UPS shutdown (complete discharge) on its own ,  Hassio which has shutdown will not get restarted automatically as UPS load will not reset.
Also this is causing UPS battery to completely discharge (0%) and shutdown. I wanted UPS to shutdown when 15% of battery is left.

**Comment by sinclairpaul** [comment]
Looking at this more, I doubt this is something we can fix.  As you have stated, and from what I can see, the power off UPS command is passed off to init, which although we could do this in some way from the container, the host would not be shutdown.  We would then be powering off the UPS, and killing all power.

If this behaviour is important to you, the only thing I could recommend  is running NUT externally somewhere and using the addon as a client.

**Comment by abhi23768** [comment]
Running NUT externally on other machine (just to shutdown UPS) can be an option but if add-on can be updated that will be great.  

Is there any way to provide access / include command line NUT client tools such 'upscmd' or 'upsdrvctl' ? These can be used through scripts or Node Red to shut down UPS. I have set ups.delay.shutdown=180; The idea is to first call UPS shutdown (upscmd ups shutdown.return or upsdrvctl shutdown) and then can call Hassio shutdown (UPS will provide power for 3 minutes for clean HA shutdown).
 
I am sure many folks are using Home Assistant as critical system and would like to use NUT addon for  clean shutdown and smooth restart after a prolong Power failure.  This will implement NUT functionality to the fullest

**Comment by sinclairpaul** [comment]
The addon already supports running in both server and client mode, please refer to the documentation.  Obviously any setup of NUT externally would be down to teh user.

As I stated before the UPS shutdown is handed off to init, i.e. handled by the shutdown process of the OS.  I don't see a way that we can cleanly duplicate this in a docker container, as you will never know what the host OS is doing.

I appreciate your ask, and as always PR's are welcomed, but I really don't see a way to implement without causing other issues.  Of course I could be wrong and someone may have a better solution.

**Comment by abhi23768** [comment]
I have opened PR with a possible solution. I have locally tested it and it works for me

**Comment by Adorem** [comment]
Is there any reason (except that now it need a rebase) why the corresponding PR was not take in account?

**Comment by jrob** [comment]
Are there any plans for this to get merged?

**Comment by jrob** [comment]
Did this get merged?

**Comment by frenck** [comment]
no
