### ISSUE TITLE
Server not listening on port 3943

### ISSUE THREAD

**Issue by rickthegeek** [hassio-addons/addon-nut#351]
# Problem/Motivation

Could not connect to server using the NUT device integration

## Expected behavior

Entered known good username and password, and expected integration to connect

## Actual behavior

Received "failed to connect" message no matter what I enter for username or password

## Steps to reproduce

Install NUT server addon and NUT device integration and try to connect

## Proposed changes

Change the configuration in upsd.conf to add 3493 (the port number) after the LISTEN 0.0.0.0, and update the documentation to advise it may be needed to expose the port on the addon config page. This made it work for me on a Raspberry pi 4

**Comment by sinclairpaul** [comment]
As per the docs `Note: The host a0d7b954-nut can be used to allow Home Assistant to communicate directly with the addon`

Alternatively you can change the network configuration in the addon to expose the port.
