### ISSUE TITLE
Two identical Cyberpower UPS's

### ISSUE THREAD

**Issue by RadDip** [hassio-addons/addon-nut#352]
# Problem/Motivation

> I am using a Raspberry Pi 4 installed with HAOS running the NUT add-on and Integration.   I have two identical Cyberpower SX650U UPS's connected via USB to the Pi at the same time.   The NUT add on log sees both.  But only the first one listed as a device is loaded.   The second one is ignored and stops the add on.   When I configure the add on for only one device it loads and works fine.   Since these UPS's are identical, their model, product id, vendor id, serial id are all identical.  There is absolutely no distinguishing factors between the two that separates them apart from each other.   

## Expected behavior

> Have both UPS's recognized and loaded in the NUT add on

## Actual behavior

As mentioned above, only one is recognized and loaded

## Steps to reproduce

> Various configurations were made in the configuration file tab.

## Proposed changes

> Looking to see if their is a resolution to this issue

**Comment by sinclairpaul** [comment]
I would of thought serial number should be unique, if not there really isn't much that can be done here.

**Comment by RadDip** [comment]
Ok.  Thanks for the response
