### ISSUE TITLE
Data stale error

### ISSUE THREAD

**Issue by gary-sargent** [hassio-addons/addon-nut#353]
# Problem/Motivation

Network UPS Tools add-on has previously been working fine, but in the last week or so (possibly since the latest update to HAOS/Supervisor) I'm seeing odd behaviour. After running fine for a day or two, the add-in appears to stop working (my NAS which connects to this says it is disconnected), and the logs are full of "Data stale" errors. Restarting the add-in fixes the issue for a day or so.

![image](https://github.com/hassio-addons/addon-nut/assets/17254098/f6752c93-df20-496e-8164-be97dbb1f7c3)

Core 2024.2.5
Supervisor 2024.03.0
Operating System 12.0

Running on HA Yellow.

**Comment by vordenken** [comment]
Could this be reopened? I have the same problem...
Would be great if the add-on restarts automatically if it looses connection to the ups.
