### ISSUE TITLE
Wrong Output Voltage value

### ISSUE THREAD

**Issue by KameDomotics** [hassio-addons/addon-nut#358]
Output Voltage sensor reports an incorrect value.

## Expected behavior

The Output Voltage sensor should report a value between 230 and 240 V.

## Actual behavior

Actually this sensor reports an incorrect value of 7 - 9 V maximum

**HW and SW information:**

Home Assistant Core 2024.5.1 
Home Assistant OS 12.2
UPS Model Cyber Power PR1500LCDRT2U 

**Other Details**

By manually installing an old version (0.110 dev), the Output Voltage sensor works correctly, displaying a correct value.
![IMG_8165](https://github.com/hassio-addons/addon-nut/assets/47695661/1bb1c6d6-f2c0-424b-9095-59801717af6f)

By installing the latest version (0.113) officially from Supervisor, the Output Voltage sensor shows the wrong value.

**Add-On Setup**

![IMG_8166](https://github.com/hassio-addons/addon-nut/assets/47695661/bf273f78-7576-4d27-b694-dc1083efe2e6)

Finally, with the latest versions of Home Assistant Core (from 2024.4.4) this error appears continuously:
![IMG_8167](https://github.com/hassio-addons/addon-nut/assets/47695661/9ae0209c-3576-422d-96a1-b995c2d73707)

**Comment by sinclairpaul** [comment]
Although it appears you are logging an issue with the integration, I don't see why this would occur as the version of NUT hasn't changed.  It would be great if you could try the various versions after so we could narrow down the commit that caused this.

The errors you pasted are to do with your local copy of the addon.

**Comment by sinclairpaul** [comment]
Thanks, though it isn't very descriptive, unless we can nail down the version that caused the issue I doubt there can be much done here.  As the issue is specific to the hardware you run, it is tricky to reproduce.
