### ISSUE TITLE
No temperature entity for APC SMT1500i

### ISSUE THREAD

**Issue by cristianstoica** [hassio-addons/addon-nut#364]
# Problem/Motivation

Temperature entity missing in the Integration. Checked disabled entities and still not found.

## Expected behavior

Show the UPS temperature.

## Actual behavior

Temperature entity missing.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Integrations are part of Home Assistant, not the addon.

**Comment by cristianstoica** [comment]
Information about temperature should be provided by the NUT server, shouldn't it? The NUT server page https://networkupstools.org/ddl/APC/Smart-UPS_1500.html lists battery.temperature as a supported variable yet it is not found on the NUT integration status page, presumably because it's not provided by the NUT server? I understand that this add-on is based on the NUT server 2.8.0. Even though 2.8.2. is the most current, information about battery temperature on the SMT1500 was available from at least 2.7.1. What could be wrong here?
