### ISSUE TITLE
Add support for apc_modbus

### ISSUE THREAD

**Issue by TimBeekman** [hassio-addons/addon-nut#367]
# Problem/Motivation

The apc_modbus driver is needed for communication with my UPS

## Expected behavior

When i configure the add-on like this:
- name: myups
  driver: apc_modbus
  port: auto
  config:
    - vendorid = 051d

I expected the driver to be loaded.

## Actual behavior

The follwoing message is shown in the logs:
Can't start /lib/nut/apc_modbus: No such file or directory

## Proposed changes

Embed the apc_modbus in the package, or make it possible for the end user to do so

**Comment by sinclairpaul** [comment]
This looks like it would require a custom NUT build, which isn't something we really want to do.

If you need the functionality I would suggest not using the addon.
