### ISSUE TITLE
Cannot Connect to NUT Server

### ISSUE THREAD

**Issue by IronSheepdog** [hassio-addons/addon-nut#37]
Forgive me as I am new to Home Assistant and to this add-on. I installed the NUT add-on and added the necessary info the configuration.yaml. I go to Configuration>Integrations to add the Network UPS Tools (NUT) and not matter what I do, I get a "Failed to connect, please try again" error. I should add that I am running this on Hassio on a Raspberry Pi 4.

Here is my configuration.yaml entry:
sensor:
  - platform: nut
    name: "Basement UPS"
    host: localhost
    username: lcbingman
    password: Hellfire50!
    resources:
      - ups.status

Here is what is in the NUT config section:
users:
  - username: username
    password: password
    instcmds:
      - all
    actions:
      - set
      - fsd
devices:
  - name: mainups
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'
list_usb_devices: 'true'

And here is the log file for the NUT:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.1.2
 You are running the latest version of this add-on.
 System: HassOS 3.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.108.3
 Home Assistant Supervisor: 217
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[11:44:15] INFO: Setting mode to netserver...
[11:44:15] INFO: Connected USB devices:
Bus 001 Device 003: ID 0658:0200 Sigma Designs, Inc. Aeotec Z-Stick Gen5 (ZW090) - UZB
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[11:44:15] INFO: Generating /etc/nut/upsd.users...
[11:44:16] INFO: Configuring user: username
[11:44:16] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[11:44:18] INFO: Configuring Device named mainups...
[11:44:18] INFO: Starting the UPS drivers...
Network UPS Tools - UPS driver controller 3.8.0-3396-gcdc7c4b5b1
Network UPS Tools - Generic HID driver 0.41 (3.8.0-3396-gcdc7c4b5b1)
Using subdriver: APC HID 0.96
USB communication driver 0.33
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:44:18] INFO: Starting the UPS information server...
Network UPS Tools upsd 3.8.0-3396-gcdc7c4b5b1
   0.000000	fopen /var/run/nut/upsd.pid: No such file or directory
   0.000399	listening on 0.0.0.0 port 3493
   0.000957	Connected to UPS [mainups]: usbhid-ups-mainups
[11:44:18] INFO: Starting the UPS monitor and shutdown controller...
Network UPS Tools upsmon 3.8.0-3396-gcdc7c4b5b1
   0.000000	fopen /var/run/upsmon.pid: No such file or directory
   0.000464	Using power down flag file /etc/killpower
   0.000832	UPS: mainups@localhost (master) (power value 1)
   0.000937	debug level is '1'
   0.009951	Trying to connect to UPS [mainups@localhost]
   0.028922	User upsmonmaster@127.0.0.1 logged into UPS [mainups]
   0.011223	Logged into UPS mainups@localhost

**Comment by sinclairpaul** [comment]
For host please use `a0d7b954-nut`

https://github.com/hassio-addons/addon-nut#about

**Comment by IronSheepdog** [comment]
That worked! Thanks! I guess I assumed the host value was relative to each install.
