### ISSUE TITLE
Addon  doesn't exist

### ISSUE THREAD

**Issue by PaulBiod** [hassio-addons/addon-nut#376]
Hi,
since a while now, the addon is not available.
If I try to install from the "add addon" button on your doc, I get : 
![image](https://github.com/user-attachments/assets/87ce4753-01d3-4d8c-808b-5dfa864f68ee)

If I try directly from the addon section of home assistant, I get : 
![image](https://github.com/user-attachments/assets/2a9914c1-ab8f-4e8d-942a-846e2b3e699b)

Another weird thing, in my official addons listing, NUT is not there anymore : 
![image](https://github.com/user-attachments/assets/436ea4b8-b581-47fc-b3f5-0004260b02d6)

So, I don't understand how to install the addon...
Thanks for helping

**Comment by sinclairpaul** [comment]
It's an issue with Home Assistant itself, not the addon, you may want to try a reboot, if it still persists I would suggest logging the issue upstream.

**Comment by PaulBiod** [comment]
Solved !
Thanks to this post : 
https://community.home-assistant.io/t/ha-not-displaying-community-add-ons/715041/2

had to add a slash at the end of url when addind the repo, like : 
https://github.com/hassio-addons/repository/
