### ISSUE TITLE
Permissions errors when using Serial

### ISSUE THREAD

**Issue by maslyankov** [hassio-addons/addon-nut#38]
# Problem/Motivation

same as here - https://github.com/hassio-addons/addon-nut/pull/33

current config: 
devices:
  - name: myups
    driver: apcsmart
    port: /dev/ttyUSB0
    config: []
mode: netserver
shutdown_host: 'false'

(Devices are seen when listed)

## Expected behavior

Connect to ups. (Tested in raspbian with nut and works)

## Actual behavior

> [17:52:10] INFO: Starting the UPS drivers...
> Network UPS Tools - UPS driver controller 3.8.0-3396-gcdc7c4b5b1
> Network UPS Tools - APC Smart protocol driver 3.1 (3.8.0-3396-gcdc7c4b5b1)
> Fatal error: unusable configuration
> APC command table version 3.1
> 
> Unable to open /dev/ttyUSB0: Permission denied
> 
>   Current user id: nut (100)
> Serial port owner: root (0)
> Serial port group: dialout (20)
>      Mode of port: 0660

## Steps to reproduce

1. Setup Hass.io addon Nut

2. Setup APC Smart ups (which uses serial)

3. Connect Server to UPS using: USB to Serial (if no serial available), 940-0024C Cable.

4. Run Nut server in Addon.

5. Get permissions errors.

## Proposed changes

https://github.com/home-assistant/supervisor/issues/1614

> "It's docker, you should run the software as root not as nut." 

Is there a way to run it as root?

**Comment by ben-digitalhive** [comment]
Has there been any progress on this issue?   I am running on a NUC and get this permission issue.

`[17:55:54] INFO: Starting the UPS drivers...
Network UPS Tools - UPS driver controller 3.8.0-3220-g866b921892
Network UPS Tools - Megatec/Q1 protocol serial driver 1.57 (3.8.0-3220-g866b921892)
Fatal error: unusable configuration
Driver failed to start (exit status=1)
Unable to open /dev/ttyS0: Permission denied
  Current user id: nut (100)
Serial port owner: root (0)
Serial port group: audio (18)
     Mode of port: 0660
Things to try:
 - Use another port (with the right permissions)
 - Fix the port owner/group or permissions on this port
 - Run this driver as another user (upsdrvctl -u or 'user=...' in ups.conf).
   See upsdrvctl(8) and ups.conf(5).
[cont-init.d] nut.sh: exited 1.`

**Comment by maslyankov** [comment]
> Has there been any progress on this issue? I am running on a NUC and get this permission issue.
> 
> > [17:55:54] INFO: Starting the UPS drivers...
> > Network UPS Tools - UPS driver controller 3.8.0-3220-g866b921892
> > Network UPS Tools - Megatec/Q1 protocol serial driver 1.57 (3.8.0-3220-g866b921892)
> > Fatal error: unusable configuration
> > Driver failed to start (exit status=1)
> > Unable to open /dev/ttyS0: Permission denied
> > Current user id: nut (100)
> > Serial port owner: root (0)
> > Serial port group: audio (18)
> > Mode of port: 0660
> > Things to try:
> > 
> > * Use another port (with the right permissions)
> > * Fix the port owner/group or permissions on this port
> > * Run this driver as another user (upsdrvctl -u or 'user=...' in ups.conf).
> >   See upsdrvctl(8) and ups.conf(5).
> >   [cont-init.d] nut.sh: exited 1.

Nope, nothing new here :(

**Comment by Sergey-SRG** [comment]
> # Problem/Motivation
> same as here - #33
> 
> current config:
> devices:
> 
> * name: myups
>   driver: apcsmart
>   port: /dev/ttyUSB0
>   config: []
>   mode: netserver
>   shutdown_host: 'false'
> 
> (Devices are seen when listed)
> 
> ## Expected behavior
> Connect to ups. (Tested in raspbian with nut and works)
> 
> ## Actual behavior
> > [17:52:10] INFO: Starting the UPS drivers...
> > Network UPS Tools - UPS driver controller 3.8.0-3396-gcdc7c4b5b1
> > Network UPS Tools - APC Smart protocol driver 3.1 (3.8.0-3396-gcdc7c4b5b1)
> > Fatal error: unusable configuration
> > APC command table version 3.1
> > Unable to open /dev/ttyUSB0: Permission denied
> > Current user id: nut (100)
> > Serial port owner: root (0)
> > Serial port group: dialout (20)
> > Mode of port: 0660
> 
> ## Steps to reproduce
> 1. Setup Hass.io addon Nut
> 2. Setup APC Smart ups (which uses serial)
> 3. Connect Server to UPS using: USB to Serial (if no serial available), 940-0024C Cable.
> 4. Run Nut server in Addon.
> 5. Get permissions errors.
> 
> ## Proposed changes
> [home-assistant/supervisor#1614](https://github.com/home-assistant/supervisor/issues/1614)
> 
> > "It's docker, you should run the software as root not as nut."
> 
> Is there a way to run it as root?

 sudo chmod 666 /dev/ttyS0

**Comment by Sergey-SRG** [comment]
> Has there been any progress on this issue? I am running on a NUC and get this permission issue.
> 
> > [17:55:54] INFO: Starting the UPS drivers...
> > Network UPS Tools - UPS driver controller 3.8.0-3220-g866b921892
> > Network UPS Tools - Megatec/Q1 protocol serial driver 1.57 (3.8.0-3220-g866b921892)
> > Fatal error: unusable configuration
> > Driver failed to start (exit status=1)
> > Unable to open /dev/ttyS0: Permission denied
> > Current user id: nut (100)
> > Serial port owner: root (0)
> > Serial port group: audio (18)
> > Mode of port: 0660
> > Things to try:
> > 
> > * Use another port (with the right permissions)
> > * Fix the port owner/group or permissions on this port
> > * Run this driver as another user (upsdrvctl -u or 'user=...' in ups.conf).
> >   See upsdrvctl(8) and ups.conf(5).
> >   [cont-init.d] nut.sh: exited 1.

sudo chmod 666 /dev/ttyS0

**Comment by ben-digitalhive** [comment]
Im happy tip test this suggested chmod change but where do i do it? Inside the nut container?  How?  Sorry im not a noob but docker is new for me. 

sudo chmod 666 /dev/ttyS0

**Comment by DaAwesomeP** [comment]
To link to related issues:
https://github.com/hassio-addons/addon-nut/issues/32 (same issue, but was closed as a supervisor issue)
https://github.com/hassio-addons/addon-nut/pull/33 (pull to manually fix permission, closed as a supervisor issue)
https://github.com/home-assistant/supervisor/issues/1614 (supervisor issue, closed saying nothing can be done on the supervisor end to fix using non-root with existing files)

The potential fixes are to add permissions fixes as I did in #33 (works but is improper) or to run NUT as root. But @sinclairpaul said on Discord that getting it to run as root doesn't work. I will try this soon too.

**Comment by DaAwesomeP** [comment]
@ben-digitalhive applying the permissions fix from #33 on your machine locally would probably be best accomplished by downloading the addon from my fork with the fix and installing it as a local addon. That way the fix will be sustained across restarts/rebuilds/reinstalls.

**Comment by ben-digitalhive** [comment]
> @ben-digitalhive applying the permissions fix from #33 on your machine locally would probably be best accomplished by downloading the addon from my fork with the fix and installing it as a local addon. That way the fix will be sustained across restarts/rebuilds/reinstalls.
> 
> However, I would honestly recommend that waiting for a proper fix would be best.

I think i will wait. While it would be nice to have visbility of the UPS state its not critical.

**Comment by sinclairpaul** [comment]
I have pushed a fix which should be available on the Edge repo to run as root.  I have tested with a USB device which appears to be fine.  It would be great if anyone with the issue could validate and test?

**Comment by maslyankov** [comment]
> I have pushed a fix which should be available on the Edge repo to run as root. I have tested with a USB device which appears to be fine. It would be great if anyone with the issue could validate and test?

Hmm. Just tried but seems like the update is pending. (still downloading  eafc871 for me) Will tell in a few hours I guess.

**Comment by DaAwesomeP** [comment]
Mine shows latest commit, and I gave it a try and it seems to work!
```
13:19:32] INFO: Starting the UPS drivers...
Network UPS Tools - UPS driver controller 3.8.0-3220-g866b921892
Network UPS Tools - Generic contact-closure UPS driver 1.36 (3.8.0-3220-g866b921892)
UPS type: CyberPower Power99
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:19:34] INFO: Starting the UPS information server...
Network UPS Tools upsd 3.8.0-3220-g866b921892
   0.000000	fopen /var/run/nut/upsd.pid: No such file or directory
   0.001689	listening on 0.0.0.0 port 3493
   0.004721	Connected to UPS [ups1]: genericups-ups1
[13:19:34] INFO: Starting the UPS monitor and shutdown controller...
Network UPS Tools upsmon 3.8.0-3220-g866b921892
   0.000000	fopen /var/run/upsmon.pid: No such file or directory
   0.000929	Using power down flag file /etc/killpower
   0.001637	UPS: ups1@localhost (master) (power value 1)
   0.003860	debug level is '1'
   0.003906	Warning: running as one big root process by request (upsmon -p)
   0.027174	Trying to connect to UPS [ups1@localhost]
   0.072858	User upsmonmaster@127.0.0.1 logged into UPS [ups1]
   0.028130	Logged into UPS ups1@localhost
```
This is with a hardware serial port `/dev/ttyS0`. I restarted the host before trying because the modified version of the addon I was using modified permissions on `/dev/tty*`, so this should be clean test.

**Comment by maslyankov** [comment]
> I have pushed a fix which should be available on the Edge repo to run as root. I have tested with a USB device which appears to be fine. It would be great if anyone with the issue could validate and test?

This seems to fix the issue! Working flawlessly! :) Thank you.
