### ISSUE TITLE
Allow option for minsupplies to be 0. 

### ISSUE THREAD

**Issue by skaggerik** [hassio-addons/addon-nut#382]
# Problem/Motivation

One UPS is configured, which should never shut down HA or addon. Therefore Powervalue was set to 0. 

## Expected behavior

Addon would run as normal, but never be shut down by UPS low battery. 

## Actual behavior

Addon crashed: 

```
Fatal error: insufficient power configured!

Sum of power values........: 0
Minimum value (MINSUPPLIES): 1

Edit your upsmon.conf and change the values.
[11:14:42] WARNING: upsmon crashed, halting add-on
```

## Steps to reproduce

Use this configuration: 

- name: backups
  driver: usbhid-ups
  port: auto
  powervalue: 1
  config: []

## Proposed changes

Allow for a powervalue of 0 with only one UPS. Allow minsupplies to be 0?

**Comment by sinclairpaul** [comment]
See #368
