### ISSUE TITLE
New version of NUT?

### ISSUE THREAD

**Issue by miggland** [hassio-addons/addon-nut#385]
# Problem/Motivation

My UPS (Eaton 5P 850 G2) has issues with NUT < 2.8.1. This add-on uses 2.8.0.

The issue is that the communication is dropped when the UPS goes ONBATT - something which no longer occurs in new NUT. This problem is not specific to this add-on.

## Proposed changes

An update of the NUT version should fix my issues.

**Comment by frenck** [comment]
The version of NUT provided is the latest available in the distro used.

../Frenck
