### ISSUE TITLE
[Unknown] ERR DATA-STALE issue (with possible solution)

### ISSUE THREAD

**Issue by OdinVex** [hassio-addons/addon-nut#389]
# Problem/Motivation

I recently redesigned my network and I couldn't get NUT working correctly. Under Devices the entry (localhost) would throw an error: "...ERR DATA-STALE" Rebooting HAOS did not help but oddly enough manually restarting the `addon_a0d7b954_nut` docker worked.

## Possible Solution

`docker restart addon_a0d7b954_nut` via SSH on port 22222. I wish there was a way to restart the container from the UI? Maybe there is? Learning HAOS still. (Worst mistake was going with HAOS instead of an Ubuntu server with HA installed instead...)

**Comment by sinclairpaul** [comment]
You can restart the addon from the addon page (where it was configured and installed).
As this isn't an issue with the addon will close this out.

**Comment by sinclairpaul** [comment]
I would suggest there is a different issue, as well a docker restart is no different from the UI restart or a reboot.

If you have a Cyberpower UPS I would suggest searching the issues, but this really is a hardware thing.

**Comment by sinclairpaul** [comment]
From your description then it's an issue with the integration ` I was pcapping`

Either way glad you had it resolved, again, restarting the addon, restarting the container, rebooting is really no different so wouldn't suggest that manually restarting containers is necessary.
