### ISSUE TITLE
NUT 0.1.2 - under HassOS 3.13 Error adding custom device "/dev/bus/usb": no such file or directory

### ISSUE THREAD

**Issue by datdamnzotz** [hassio-addons/addon-nut#39]
# Problem/Motivation
Trying to monitor APC snmp device, which doesn't use USB.

```
20-04-27 17:49:23 INFO (SyncWorker_4) [supervisor.docker.interface] Clean addon_a0d7b954_nut application
20-04-27 17:49:23 ERROR (SyncWorker_4) [supervisor.docker] Can't start addon_a0d7b954_nut: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/bus/usb": no such file or directory")
20-04-27 17:49:23 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:472> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 493, in start
    raise AddonsError() from None
supervisor.exceptions.AddonsError
```

## Expected behavior

Have a option to turn off searching for USB devices? 

## Actual behavior

Error above

## Steps to reproduce

HA -> Add Network UPS Tools plugin from store, config it to:

```yaml
users:
  - username: user
    password: 'pass'
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: dummy-ups
    port: dummy.dev
    config: []
  - name: apcups
    driver: snmp-ups
    port: 192.168.1.242
    config:
      - snmp_version = v1
      - community = public
      - pollfreq = 30
      - desc = APC UPS
mode: netclient
shutdown_host: 'false'
log_level: trace
fake_usb_devices: true
```

## Proposed changes

Perhaps a `skip_usb_devices: true`

**Comment by sinclairpaul** [comment]
The addon isn't starting at this point, so there is nothing that can be done.

What hardware is this running on that doesn't appear to have any serial devices?

**Comment by datdamnzotz** [comment]
> The addon isn't starting at this point, so there is nothing that can be done.
> 
> What hardware is this running on that doesn't appear to have any serial devices?

Correct it doesn't have any usb/serial devices.
It's a HassOS 3.13 VM under ESXi
I want to monitor via SNMP/Network/ snmp-ups

**Comment by sinclairpaul** [comment]
Add a dummy usb device so that the addon starts.

We can't do anything about this from an addon perspective.
