### ISSUE TITLE
Cannot access community forum

### ISSUE THREAD

**Issue by pove** [hassio-addons/addon-nut#4]
# Problem/Motivation
On the support section of the README.md, it is mentioned the Home Assistant [Community Forum](https://community.home-assistant.io/t/community-hass-io-add-on-network-ups-tools/68516) of this add-on.

However, this link it is not accessible, this message is shown:

> Sorry, you don't have access to that topic!

## Expected behavior

I expected to have access to the topic, as in many other add-on.

## Actual behavior

The topic is not accesible.

## Steps to reproduce

Go to the link [https://community.home-assistant.io/t/community-hass-io-add-on-network-ups-tools/68516](https://community.home-assistant.io/t/community-hass-io-add-on-network-ups-tools/68516)

## Proposed changes

Give access to this topic.

<blockquote><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-network-ups-tools/68516">Home Assistant Community</a></strong></div><div>Open source home automation that puts local control and privacy first.</div></blockquote>

**Comment by frenck** [comment]
@pove Thank you for your issue. The reasoning for this is that this add-on is not released yet.
![image](https://user-images.githubusercontent.com/195327/55390587-c77e0d80-5537-11e9-85e3-c8bc167bac85.png)
