### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by jp181278** [hassio-addons/addon-nut#40]
using a password with special characters like @ or # mine was @1234567890# the add-on require the '' and hassio is not able to connect the integration when you try, the only feedback that it gives you back is that is not able to connect

**Comment by sinclairpaul** [comment]
It's to do with how the config is written into the files.  For now if you want to use those characters they will need to be escaped with a `/` 

May possibly look to change in the future.

**Comment by jp181278** [comment]
maybe it's enought to write it down in the readme in the github

**Comment by sinclairpaul** [comment]
Rechecked this:
```users:
  - username: nutty
    password: '@1234567890#'
```

Works find and I see the correct password in the upsd.users.  Will close it out (please use single quotes rather than double).
