### ISSUE TITLE
Njoy Aster 1k working 

### ISSUE THREAD

**Issue by ImNewty** [hassio-addons/addon-nut#400]
I got the Njoy Aster 1k working and it exposes these entities to home assistant ![Screenshot_20241219-133152.png](https://github.com/user-attachments/assets/7b4d0f15-8494-4b18-a398-7b918011e4a9)

![Screenshot_20241219-133206.png](https://github.com/user-attachments/assets/828ee792-6da0-4ec4-928e-2b5479700241)

Driver: usbhid-ups
Is there a way to get battery temp? and I would love to get load in Watts and not only in %

**Comment by ImNewty** [comment]
Also when I disconnect it and reconnect it back to usb it doesn't get recognized untill I restart the addon

**Comment by sinclairpaul** [comment]
The addon provides the NUT software <https://networkupstools.org/> , the attributes that are presented are whatever the driver supports.

I would expect any disconnect/reconnect would be expected behavior as it scans on start-up

**Comment by ImNewty** [comment]
And what would explain (I forgot to mention in the original post) the output voltage saying it's 24V when it's 230V?
