### ISSUE TITLE
Tecnoware ERA 1500

### ISSUE THREAD

**Issue by danygi79** [hassio-addons/addon-nut#44]
# Problem/Motivation
addon not start

## Actual behavior

i use this configuration:
users:
  - username: nutuser
    password: edsdf3
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: blazer_usb
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'

log is this:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.2.0
 You are running the latest version of this add-on.
 System: HassOS 4.9  (armv7 / raspberrypi4)
 Home Assistant Core: 0.110.5
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[00:56:43] INFO: Setting mode to netserver...
[00:56:43] INFO: Generating /etc/nut/upsd.users...
[00:56:43] INFO: Configuring user: nutuser
[00:56:44] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[00:56:45] INFO: Configuring Device named myups...
[00:56:45] INFO: Starting the UPS drivers...
Network UPS Tools - UPS driver controller 3.8.0-3396-gcdc7c4b5b1
Network UPS Tools - Megatec/Q1 protocol USB driver 0.12 (3.8.0-3396-gcdc7c4b5b1)
Supported UPS detected with megatec/old protocol
Rating information unavailable
Vendor information unavailable
No values provided for battery high/low voltages in ups.conf
Using 'guestimation' (low: -0.866667, high: -1.083333)!
Battery runtime will not be calculated (runtimecal not set)
Startup timer elapsed, continuing...
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

I try to set vendorid and productid but not change

I've tried everything, I don't understand why it doesn't work

Best regards
        Giacomazzi Daniele

**Comment by sinclairpaul** [comment]
Hardware compatibility for the software is listed at https://networkupstools.org/stable-hcl.html

Unfortunately the addon wraps the existing software, so we cannot fix upstream issues.

**Comment by jp181278** [comment]
I don't know if it can be of help but I have configured my tecnoware era 1100 plus this way:

users:
  - username: jeanpaul
    password: jeanpaul_ups
    instcmds:
      - all
    actions: []
devices:
  - name: UPS_ERA+
    driver: blazer_usb
    port: auto
    config:
      - 'runtimecal = 230,100,450,50'
mode: netserver
shutdown_host: 'false'

Then I have set the port 3493 in the network Settings don't leave the space empty..... 

The start the addon if it doesn't work try to unplug and Plug again the usb cable

Let me know 
​
