### ISSUE TITLE
No matching HID UPS found

### ISSUE THREAD

**Issue by Romario1972** [hassio-addons/addon-nut#45]
# Problem/Motivation

>when I'm trying to start add-on I've got an error(in log):

No matching HID UPS found
Driver failed to start (exit status=1)
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 

-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
> the same issue: #21 

## Expected behavior

> I'm expecting it will run
## Actual behavior

> add-on stops

## Steps to reproduce

> Install NUT add-on, configure it and run.
 my config:

`users:
  - username: nut
    password: mypassword
    instcmds:
      - all
    actions: []
devices:
  - name: apc_ups
    driver: usbhid-ups
    port: auto
    config:
      - ignorelb
mode: netserver
shutdown_host: 'false'
vendorid: 051d`

## Proposed changes

> **possible cause**: add-on worked perfectly till I've reconfigure UPS to remove Green Power mode because it cut power after 15 minutes. Now it power my HA RPI 4 for more then 2 hours (tested)  but can't be monitored...
> any ideas?

**Comment by sinclairpaul** [comment]
I would recommend referring to the NUT documentation (https://networkupstools.org/).  You may wish to try setting the `list_usb_devices: 'true'` option to see what is detected.
