### ISSUE TITLE
It fails to start after the latest update. Add-on version: 0.2.1

### ISSUE THREAD

**Issue by pmitev** [hassio-addons/addon-nut#46]
# Problem/Motivation

It fails to start after the latest update.

## Actual behavior

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.114.3
 Home Assistant Supervisor: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[14:09:37] INFO: Setting mode to netserver...
[14:09:37] INFO: Generating /etc/nut/upsd.users...
[14:09:38] INFO: Configuring user: monuser
[14:09:40] INFO: Configuring Device named ups...
[14:09:41] INFO: Starting the UPS drivers...
Error relocating /usr/sbin/upsdrvctl: __select_time64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __difftime64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __gettimeofday_time64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __stat_time64: symbol not found
[cont-init.d] nut.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by SBastrykin** [comment]
identical error

**Comment by larzn** [comment]
Same for me.
After apply the update to version 0.2.1, the addons don't start. 
Platform: hassio
HA: 0.114.3
Addons log:
[19:15:41] INFO: Starting the UPS drivers... Error relocating /usr/sbin/upsdrvctl: __select_time64: symbol not found Error relocating /usr/sbin/upsdrvctl: __difftime64: symbol not found Error relocating /usr/sbin/upsdrvctl: __gettimeofday_time64: symbol not found Error relocating /usr/sbin/upsdrvctl: __stat_time64: symbol not found [cont-init.d] nut.sh: exited 127. [cont-finish.d] executing container finish scripts... [cont-finish.d] 99-message.sh: executing...

**Comment by TallPaul78** [comment]
Just the same

**Comment by mrpicker** [comment]
Same error for me using raspberry4, hassio x86 version.
Thank you

**Comment by mastameista** [comment]
Same error in my installation. 

Raspi4, HassOS 4.12, supervisor 235

**CONFIG**
users:
  - username: something
    password: blubb
    instcmds:
      - all
    actions: []
devices:
  - name: ups
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'true'

**ERROR-LOG**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.114.3
 Home Assistant Supervisor: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[12:28:44] INFO: Setting mode to netserver...
[12:28:44] INFO: Generating /etc/nut/upsd.users...
[12:28:45] INFO: Configuring user: upsaddon
[12:28:45] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[12:28:46] INFO: Configuring Device named ups...
[12:28:46] INFO: Starting the UPS drivers...
Error relocating /usr/sbin/upsdrvctl: __select_time64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __difftime64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __gettimeofday_time64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __stat_time64: symbol not found
[cont-init.d] nut.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by Electronlibre2012** [comment]
same error

**Comment by julnobugs** [comment]
Exact same error.
Env details:
-----------------------------------------------------------
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
-----------------------------------------------------------

**Comment by pippuzca** [comment]
Same error here

Info:
```
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
```

**Comment by zimgui** [comment]
Same error in my Home assistant system running in a raspberry Pi4, here is my config:

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.3
supervisor | 235
timezone | Europe/Madrid
version | 0.114.4
virtualenv | false

**Comment by jumping2000** [comment]
same error for me!
`
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 9 (stretch)  (amd64 / qemux86-64)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
`

**Comment by Gawronnek** [comment]
same error for me!
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235

 my config:
users:
  - username: xxxxxxxxx
    password: xxxxxx
    instcmds:
      - all
    actions: []
devices:
  - name: GreenCell
    driver: blazer_usb
    port: auto
    config: []
mode: netserver
shutdown_host: 'true'

**Comment by mauog** [comment]
Same issue described above with 0.2.1
No problem with the previous versione

**Comment by ha20** [comment]
Same issue

 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[20:14:09] INFO: Setting mode to netserver...
[20:14:09] INFO: Generating /etc/nut/upsd.users...
[20:14:09] INFO: Configuring user: nutty
[20:14:10] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[20:14:11] INFO: Configuring Device named ups...
[20:14:11] INFO: Starting the UPS drivers...
Error relocating /usr/sbin/upsdrvctl: __select_time64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __difftime64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __gettimeofday_time64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __stat_time64: symbol not found
[cont-init.d] nut.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...

**Comment by lelepando** [comment]
Unfortunately I'm in the exact same situation...
Does anyone know a way to roll back / downgrade the add on version? 
Thanks

**Comment by No5alive** [comment]
same error

**Comment by GitHubxtsnl** [comment]
same issue here:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
 System: HassOS 4.12  (armv7 / raspberrypi4)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[15:52:02] INFO: Setting mode to netserver...
[15:52:02] INFO: Generating /etc/nut/upsd.users...
[15:52:03] INFO: Configuring user: admin
[15:52:06] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[15:52:07] INFO: Configuring Device named apcsmartups1500...
[15:52:07] INFO: Starting the UPS drivers...
Error relocating /usr/sbin/upsdrvctl: __select_time64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __difftime64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __gettimeofday_time64: symbol not found
Error relocating /usr/sbin/upsdrvctl: __stat_time64: symbol not found
[cont-init.d] nut.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by Electronlibre2012** [comment]
> 
> 
> Unfortunately I'm in the exact same situation...
> Does anyone know a way to roll back / downgrade the add on version?
> Thanks

Hello,

sure!

Take a snapshot of a day or a few days ago, unselect all, just get the "folder Add-On" and "NUT" select and restore snapshot ;)

**Comment by cereale979** [comment]
Same error here!

**Comment by ha20** [comment]
Restored 0.2.0 from last weeks backup and switched off auto-update. 

Thanks for the suggestion and workaround.

**Comment by klim123123** [comment]
Same problem. Please fix.

**Comment by sinclairpaul** [comment]
Anyone posting who is not running on armv7 needs to add the full logs.

This isn't a particularly easy issue to resolve, so would suggest that restoring to a snapshot is the best action at this point.

**Comment by lelepando** [comment]
> > Unfortunately I'm in the exact same situation...
> > Does anyone know a way to roll back / downgrade the add on version?
> > Thanks
> 
> Hello,
> 
> sure!
> 
> Take a snapshot of a day or a few days ago, unselect all, just get the "folder Add-On" and "NUT" select and restore snapshot ;)

This was the first time I've installed this add on, since I bought a ups just a week ago.... 
Is there any way to manually install the 0.2.0 version?

**Comment by frenck** [comment]
> Is there any way to manually install the 0.2.0 version?

No there is not.

**Comment by cereale979** [comment]
Ok, I'm a noob, but there's a possibility to create a new version, 0.2.2
with the code inside the 0.2.0, so the people like me, without a backup,
can restore a working plug in? Please, I sayd 'noob' :)

Il sab 29 ago 2020, 11:52 Franck Nijhof <notifications@github.com> ha
scritto:

**Comment by sinclairpaul** [comment]
A new version of the addon has been pushed to the edge repo, it would be helpful if anyone who is comfortable and aware on how to install edge addons could test to see if it resolves the issue.

**Comment by Electronlibre2012** [comment]
Just wait for a new release.

And next time, better to make a snapshot BEFORE modify something in the config and BEFORE install an Add-On, and noob or not, that what we do...

**Comment by GaryOkie** [comment]
> A new version of the addon has been pushed to the edge repo, it would be helpful if anyone who is comfortable and aware on how to install edge addons could test to see if it resolves the issue.

I"ve reverted to NUT 2.0 via snapshot restore, and am back in business.    I also tried the NUT Edge version just now.  Good news - it starts fine - no 64bit symbol errors   (RasPi3 ARMV7 32bit).    

Unfortunately, all UPS sensors are returning "unavailable".

It would be good if others would also try the Edge version to make sure this isn't "my problem".

Note: for anyone else testing this Edge version, it will install alongside your existing NUT add-on, not replace it.   The Edge version will need to be configured again (userid/password, etc).   Be sure to stop the working 2.0 version if you have it running, before starting the Edge version.

**Comment by sinclairpaul** [comment]
> Unfortunately, all UPS sensors are returning "unavailable".

I am guessing your configuration uses the addon name `a0d7b954-nut` as per the documentation.  The Edge addon has a different name as it is on a different repo which should be `40817795-nut`

Thanks for the feedback, hopefully this will resolve the issue.

**Comment by GaryOkie** [comment]
Ah - ok, that makes sense.   The UI configuration isn't clear what I should be changing the add-on name though...

![image](https://user-images.githubusercontent.com/37629938/91639973-10ade780-e9e0-11ea-93a4-ea43323a89f9.png)

**Comment by sinclairpaul** [comment]
@GaryOkie It's not actually part of the addon, but the Home Assistant Integration itself.

**Comment by GaryOkie** [comment]
Got it, thanks.   Configuration.yaml (-platform Nut) updated with **host:  40817795-nut** and HASS restarted.

Sorry, still seeing all Nut sensors unavailable.

I have to leave now for the next hour, will be back to help debug further then.    Hopefully you will get other testers.

**Comment by kahrbomb** [comment]
> > Unfortunately I'm in the exact same situation...
> > Does anyone know a way to roll back / downgrade the add on version?
> > Thanks
> 
> Hello,
> 
> sure!
> 
> Take a snapshot of a day or a few days ago, unselect all, just get the "folder Add-On" and "NUT" select and restore snapshot ;)

This worked perfectly for me! I had removed the integration and lost some of my custom naming. Thankfully I had a 6 day old full snapshot and I had taken screen shots of the entities and copied the integration config before removal and was able to easily recreate/rename that stuff. Otherwise, I still would have been starting from scratch. I guess I need to turn off all of my auto-updates and have a little more patience on updates. I see this stuff getting broken a lot.

**Comment by sinclairpaul** [comment]
@GaryOkie Many thanks for your assistance with testing, its great to get feedback on the things we can't always validate ourselves 👍 

Closing out as the v0.3.0 release should hopefully resolve the issues.

**Comment by mastameista** [comment]
@sinclairpaul thx a lot! v0.3.0 works for me (armv7). Now the Addon starts again.

**Comment by Electronlibre2012** [comment]
@sinclairpaul thanks for the fix!

**Comment by GitHubxtsnl** [comment]
updating to release 0.3.1 solved my issue, thanks.
