### ISSUE TITLE
Error when starting addon NUT

### ISSUE THREAD

**Issue by RoosterX** [hassio-addons/addon-nut#5]
# Problem/Motivation

Error when starting addon, log for NUT shows:

INFO: Starting the UPS information server
   0.000000	fopen /var/run/nut/upsd.pid: No such file or directory

## Expected behavior

Should be working

## Actual behavior

Nothing actually happened, seems to be running but nothing shows up because rest of log shows:
Network UPS Tools upsd 3.8.0-3727-geade014bef
   0.000991	listening on 0.0.0.0 port 3493
   0.002534	Connected to UPS [myups]: usbhid-ups-myups

## Steps to reproduce

I can only speak for my APC SUA1000 usb, but just by installing and running I get the same fault.

## Proposed changes

Ok, I am far from an expert on the issue, but when searching the error I get from the log it seems there is something that is not getting the right permission.

**Comment by RoosterX** [comment]
This is running on my RPI 3, dmesg | grep usb shows:

[ 4578.947121] usb 1-1.2: new low-speed USB device number 11 using dwc_otg
[ 4579.125969] usb 1-1.2: New USB device found, idVendor=051d, idProduct=0002
[ 4579.129115] usb 1-1.2: New USB device strings: Mfr=3, Product=1, SerialNumber=2
[ 4579.132116] usb 1-1.2: Product: Smart-UPS 1000 FW:652.13.I USB FW:7.3
[ 4579.135075] usb 1-1.2: Manufacturer: American Power Conversion
[ 4579.138005] usb 1-1.2: SerialNumber: AS0729221804
[ 4579.364574] hid-generic 0003:051D:0002.0005: hiddev96,hidraw0: USB HID v1.10 Device [American Power Conversion Smart-UPS 1000 FW:652.13.I USB FW:7.3] on usb-3f980000.usb-1.2/input0

**Comment by frenck** [comment]
@RoosterX This add-on is not production ready and not published.
