### ISSUE TITLE
USB APC UPS NUT won't start 

### ISSUE THREAD

**Issue by Luc3as** [hassio-addons/addon-nut#50]
# Problem/Motivation

I was trying to migrate nut addon from initial versions where there were no UI settings, and It was doing great. However now after searching few other issues here, I found config which I think should work, I can see my USB on host, but when I added list_usb_devices: true   , I've got error unable to initialize libusb: -99 .. whole logs bellow. 

## Expected behavior

Start the addon and show connected USB devices

## Actual behavior

Addon stops with error code. unable to initialize libusb: -99

## Steps to reproduce

````bash
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: c022f38
 You are running the latest version of this add-on.
 System: Debian GNU/Linux bullseye/sid  (amd64 / qemux86-64)
 Home Assistant Core: 0.114.4
 Home Assistant Supervisor: 235
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[18:39:03] INFO: Setting mode to netserver...
[18:39:03] INFO: Connected USB devices:
unable to initialize libusb: -99
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
````
````yaml
users:
  - username: usr
    password: pass
    instcmds:
      - all
    actions: []
devices:
  - name: apcups
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 051d*
mode: netserver
shutdown_host: 'false'
list_usb_devices: true
````

![image](https://user-images.githubusercontent.com/6381468/91744750-3a226b00-ebba-11ea-9de0-249dc798f10d.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

I also tried edge version as well as community versions.

**Comment by sinclairpaul** [comment]
The error would suggest that the Supervisor is unable to pass the USB devices.  I would suggest you validate your Supervised Install against the details at https://github.com/home-assistant/supervised-installer.  Also look for issues/errors in the Supervisor log.

If the container can't see the USB bus, there isn't much we can do.

**Comment by JonGilmore** [comment]
@Luc3as did you find out the solution to this? I'm facing the same issue and I haven't had any luck figuring it out so far. NUT worked for quite a while for me, then just broke (sorta) recently.

**Comment by Luc3as** [comment]
Hey, yes, in fact I had to give up on this addon. I installed and configured NUT server right on linux, It was quite easy and running from first try. Then I added UPS to HASS through integrations pannel, there is NUT, so I can read all infos and do the automations. and then I connected my QNAP NAS through SNMP to the same NUT Server. everything working as expected. I really don't know what changed and it was beyond my time to debug this. I think there would be some additional parameter needed as you start main docker container for hass or supervisor. In every case, if you have full operating system under your installation, you could go the same way as I did.
