### ISSUE TITLE
Feature request: choose between stable (2.7.4 version) and development version (github master branch)

### ISSUE THREAD

**Issue by forast3r** [hassio-addons/addon-nut#53]
# Problem/Motivation

New UPS models and features have been incorporated in recent pull requests to NUT's github master branch.
Network UPS Tools has a very slow release rate (the current 2.7.4 version was released in 2016).

## Expected behavior

Giving the option to choose between the stable and the github version would maintain the current features but giving advanced users the chance to have new supported devices/sensors.

## Actual behavior

Actually the source code is downloaded from http://www.networkupstools.org/source/2.7/nut-2.7.4.tar.gz then uncompressed, compiled and installed.

## Steps to reproduce

n/a

## Proposed changes

Downloading the source from github ( git clone git://github.com/networkupstools/nut.git ) requires an additional step (running autogen.sh).
The remaining steps would be the same.

**Comment by sinclairpaul** [comment]
Sorry, I'm not going to add cloning from master, as it becomes very difficult to track for any support issues.

You can always fork and build a version if needed.

**Comment by forast3r** [comment]
> Sorry, I'm not going to add cloning from master, as it becomes very difficult to track for any support issues.
> 
> You can always fork and build a version if needed.

Thanks for the quick reply, I will try to build it.

> 
> Edit - Just to add, the containers are published, not built on install.

Understood. Until now only developed some local addons, so reading de Dockerfile I had supposed that it was built. I study the addon documentation.
