### ISSUE TITLE
Powerwalker VI 650 SHL LCD Not found

### ISSUE THREAD

**Issue by tactmaster** [hassio-addons/addon-nut#54]
# Problem/Motivation

Powerwalker VI 650 SHL LCD Plugged in to RPI3 Hass io (32.bit) 

```
devices:
  - name: powerwalker
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 06DA
```
## Expected behavior

finds UPS

## Actual behavior

> [14:18:06] INFO: Setting mode to netserver...
> [14:18:07] INFO: Connected USB devices:
> Bus 001 Device 005: ID 1781:0c30 Multiple Vendors Telldus TellStick
> Bus 001 Device 003: ID 0424:ec00 Microchip Technology, Inc. (formerly SMSC) SMSC9512/9514 Fast Ethernet Adapter
> Bus 001 Device 007: ID 1cf1:0030 Dresden Elektronik 
> Bus 001 Device 108: ID 06da:ffff Phoenixtec Power Co., Ltd 
> Bus 001 Device 002: ID 0424:9514 Microchip Technology, Inc. (formerly SMSC) SMC9514 Hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> [14:18:07] INFO: Generating /etc/nut/upsd.users...
> [14:18:08] INFO: Configuring user: nut
> [14:18:09] DEBUG: Password SHA1: 
> [14:18:09] DEBUG: Requested API resource: https://api.pwnedpasswords.com/range/1CC9E
> [14:18:09] DEBUG: API HTTP Response code: 200
> [14:18:09] INFO: Password is NOT in the Have I Been Pwned database! Nice!
> [14:18:12] INFO: Configuring Device named powerwalker...
> [14:18:12] INFO: Faking USB devices for Cyber Power fix...
> mknod: /dev/bus/usb/001/001: File exists
> mknod: /dev/bus/usb/001/002: File exists
> mknod: /dev/bus/usb/001/003: File exists
> mknod: /dev/bus/usb/001/005: File exists
> mknod: /dev/bus/usb/001/007: File exists
> [14:18:15] INFO: Starting the UPS drivers...
> Network UPS Tools - UPS driver controller 2.7.4
>    0.000000	Starting UPS: powerwalker
> Network UPS Tools - Generic HID driver 0.41 (2.7.4)
> No matching HID UPS found
> USB communication driver 0.33
>    0.043471	Driver failed to start (exit status=1)
> [cont-init.d] nut.sh: exited 1.

## Other Info

nut-scanner on ubuntu 

[nutdev1]
	driver = "usbhid-ups"
	port = "auto"
	vendorid = "06DA"
	productid = "FFFF"
	bus = "003"

**Comment by sinclairpaul** [comment]
Documentation for supported devices is at:

https://networkupstools.org/stable-hcl.html

**Comment by tactmaster** [comment]
Thanks for you quick reply
Look like that list if not up to date.
It was introduced in  2.6.2 https://github.com/networkupstools/nut/blob/51f519271e6c863899d52a83097e506c1c8b7a7c/NEWS#L567

A little google suggest it maybe down to udev rules. However I am unsure how hass.io/docker/udev/etc all interact :)

https://www.desktux.nl/apps:nut ?

**Comment by sinclairpaul** [comment]
The reason I pointed you at the page, is that those Powerwalker devices appear to use the blazer-usb driver, where you have usbhid-ups in your config.

Have you tried the different driver?

The udev rules are implemented by the build/install, you can see them in the container.

**Comment by tactmaster** [comment]
Ok I am pretty sure it usbhid-ups
https://github.com/networkupstools/nut/issues/483

I tried blazer-usb

> Network UPS Tools - UPS driver controller 2.7.4
> Can't start /usr/lib/nut/blazer-usb: No such file or directory
> [cont-init.d] nut.sh: exited 1.

**Comment by tactmaster** [comment]
I have been playing  a bit added nut. sh
nut-scanner

didn't find anything seems like something is not getting though the layers

> Scanning USB bus.
> Failed to open device, 						skipping. (No such device or address)
