### ISSUE TITLE
Poll UPS [myups@localhost] failed - Data stale

### ISSUE THREAD

**Issue by SHHA24** [hassio-addons/addon-nut#56]
# Problem/Motivation
NUT server Addon on supported Debian / Docker setup, USB to Belkin UPS

about 10 min the error is - Poll UPS [myups@localhost] failed - Data stale

rebooting the HA Server the addon comes back online and works fine, but then stops. 

have seen some post about adding maxage: 25 to the upsd.conf , but don't have access to that conf as its an addon. 

any advice or help. 
thanks

**Comment by sinclairpaul** [comment]
Please check the docs.

https://github.com/hassio-addons/addon-nut/blob/master/nut/DOCS.md#option-upsd_maxage
