### ISSUE TITLE
New device (same as older)

### ISSUE THREAD

**Issue by luckyzor** [hassio-addons/addon-nut#57]
# Problem/Motivation

> New device appeared in the integration but is the same device
> 
![image](https://user-images.githubusercontent.com/31155573/103703077-3444f800-4fa7-11eb-9ec2-7047e5e66304.png)

## Expected behavior

> no new device

## Actual behavior

> older device is unavailable

## Steps to reproduce

> Don't know

**Comment by sinclairpaul** [comment]
Sorry, you are referring to the integration, not the addon.
