### ISSUE TITLE
Error after update to supervisor-2021.02.5

### ISSUE THREAD

**Issue by stanislavmerts** [hassio-addons/addon-nut#80]
# Problem/Motivation

Afte supervisor update to supervisor-2021.02.5. Addon not starting
My currently running version 37c3dd6, also trying 7dc70a7
Operating System Ubuntu 20.04.1 LTS
Docker version 20.10.2
Home Assistant version 2021.1.5
Addon working perfectly, but after restart host and update supervisorits not starting

My addon config:
`users:
  - username: ######
    password: #######
    instcmds:
      - all
    actions:
      - set
devices:
  - name: upsha_local
    driver: blazer_usb
    port: auto
    config:
      - vendorid = 0665
      - productid = 5161
mode: netserver
shutdown_host: 'false'
log_level: debug
upsd_maxage: 25`

Addon log after start addon:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 37c3dd6
 There is an update available for this add-on!
 Latest add-on version: 7dc70a7
 Please consider upgrading as soon as possible.
 System: Ubuntu 20.04.1 LTS  (amd64 / intel-nuc)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.02.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[02:03:34] INFO: Setting mode to netserver...
[02:03:35] INFO: Generating /etc/nut/upsd.users...
[02:03:35] INFO: Configuring user: admin
[02:03:35] DEBUG: Password SHA1: 5C7424F57FC3B4AE7B38904830A4536848670487
[02:03:36] DEBUG: Requested API resource: https://api.pwnedpasswords.com/range/5C742
[02:03:36] DEBUG: API HTTP Response code: 200
[02:03:36] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[02:03:36] INFO: Configuring Device named upsha_local...
[02:03:37] INFO: Starting the UPS drivers...
Network UPS Tools - UPS driver controller 3.8.0-3220-g866b921892
   0.000000	Starting UPS: upsha_local
Network UPS Tools - Megatec/Q1 protocol USB driver 0.12 (3.8.0-3220-g866b921892)
No supported devices found. Please check your device availability with 'lsusb'
and make sure you have an up-to-date version of NUT. If this does not help,
try running the driver with at least 'subdriver', 'vendorid' and 'productid'
options specified. Please refer to the man page for details about these options
(man 8 blazer_usb).
   0.002771	Driver failed to start (exit status=1)
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.`

In supervisor hardware menu:
`- name: 1-6.2
    sysfs: '/sys/devices/pci0000:00/0000:00:15.0/usb1/1-6/1-6.2'
    dev_path: /dev/bus/usb/001/008
    subsystem: usb
    by_id: null
    attributes:
      BUSNUM: '001'
      DEVNAME: /dev/bus/usb/001/008
      DEVNUM: 008
      DEVPATH: '/devices/pci0000:00/0000:00:15.0/usb1/1-6/1-6.2'
      DEVTYPE: usb_device
      DRIVER: usb
      ID_BUS: usb
      ID_MODEL: USB_to_Serial
      ID_MODEL_ENC: USB\x20to\x20Serial
      ID_MODEL_ID: '5161'
      ID_REVISION: '0002'
      ID_SERIAL: INNO_TECH_USB_to_Serial_20100826
      ID_SERIAL_SHORT: '20100826'
      ID_USB_INTERFACES: ':030000:'
      ID_VENDOR: INNO_TECH
      ID_VENDOR_ENC: INNO\x20TECH
      ID_VENDOR_ID: '0665'
      MAJOR: '189'
      MINOR: '7'
      PRODUCT: 665/5161/2
      SUBSYSTEM: usb
      TYPE: 0/0/0
      USEC_INITIALIZED: '401216279'`

**Comment by sinclairpaul** [comment]
Please update to the latest release version v0.5.0 (also stop using the edge addon)

**Comment by stanislavmerts** [comment]
Ok, Thanks)
It's work!!!
