### ISSUE TITLE
Can’t Save Configuration

### ISSUE THREAD

**Issue by wes1993** [hassio-addons/addon-nut#9]
Hello, I have a TecnoWare UPS Era + 1100.
I want to use this addon but I can’t save the configuration, every time I add something the config won’t save.
I think the correct driver is blazer_usb.
Also if o copy the config in the guide without modify I can’t save...

**Comment by andriuskr** [comment]
Same issue here. Cannot save the config

**Comment by frenck** [comment]
Thanks, guys, however, please note this add-on is not released and currently not in active development.

**Comment by sblantipodi** [comment]
Pretty sad to hear that.
The add-on could be really useful. Hope that someone will have the time and the patience to make it work in the future

**Comment by frenck** [comment]
I’ve ordered an UPS myself to allow me to work on this add-on. Please be patient.

**Comment by sblantipodi** [comment]
Do you know if UPSs have some communication standards?
Is it possible to see the addon working on different brands over than APC?

APC is the worst UPS you can buy right now, they live on their "blazon" but they completely abandoned the desktop segment.
They have really old design, they are expensive and approximated sinewave is really a no go for today computers.
If you have a desktop with a PFC power supply (and if you have a desktop you must have a PFC power supply) you will hear you power supply buzzing so hard.

So, please stop supporting APC only, there are so many other brands that worth your time.
Cyberpower is the best desktop UPS manufacturer today.

They produces cheap but excellent UPS with sinewave output and they are very widespread thanks to their quality.

Just my two cents :)

**Comment by frenck** [comment]
I received that comment twice today, canceled my APC order. Will look into Cyberpower.

**Comment by garyak** [comment]
+1 for Cyberpower. Recently replaced batteries after five years. Running an Intel NUC, Ubuntu 18.04, and Hass.io install connected to Cyberpower 1500. Given some instruction, I'd be happy to test UPS integration.

**Comment by cben0ist** [comment]
Is this addon now release with the recent approved PR ? Thank you!

**Comment by frenck** [comment]
no

**Comment by cben0ist** [comment]
Got it ! Thanks ! (That was fast!!!)

**Comment by frenck** [comment]
Amazing, Right? 😉

**Comment by dale3h** [comment]
As for the original topic of the issue, the configuration is now primarily contained in files located in `/config/nut` I believe. I will update the documentation later today to reflect the configuration changes. Basically, most files now act as expected in the NUT documentation.

**Comment by dale3h** [comment]
And for what it’s worth, I have it running with both APC and CyberPower UPS devices.

@wes1993 I will do some research real quick to see if your UPS is compatible with NUT.

**Comment by dale3h** [comment]
I do not see anything about Era Plus support, but I do see support for Era LCD.

Here is a full hardware compatibility list: https://networkupstools.org/stable-hcl.html

Any device on this list *should* be supported by the add-on.

**Comment by cben0ist** [comment]
I have a CyberPower EC850LCD. I will run some tests hopefully later this week and let you know if anything.

**Comment by cben0ist** [comment]
Hey, sorry for the newbie question but... how do I install that add-on to test it ? Since it isn't release yet I cannot do it the regular way. Thank you.

**Comment by Adorem** [comment]
@cben0ist If you do not found the solution since your message see here: #17.

**Comment by sinclairpaul** [comment]
I'm going to close this out for now, as I believe the updates to the edge add on will likely have resolved the original issue.
