### ISSUE TITLE
Intel NUC APC1400 not working?

### ISSUE THREAD

**Issue by copilador** [hassio-addons/addon-nut#93]
# Problem/Motivation
Not working config. Intel Nuc + Home Assistant + UPS APC 1400U :
 Add-on version: 0.6.1
 System: Home Assistant OS 5.11  (amd64 / intel-nuc)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.6

 New installation addon-nut for UPS APC 1400U (usb)

## Expected behavior

Get data from UPS

## Actual behavior

I am NOT getting data from UPS

## Steps to reproduce
config addon-nut:
users:
  - username: xxxx
    password: xxxxx
    instcmds:
      - all
    actions: []
devices:
  - name: APC1400
    driver: usbhid-ups
    port: auto
    config:
      - vendorid =  051d*
mode: netserver
shutdown_host: 'false'
list_usb_devices: 'true'

log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.6.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.11  (amd64 / intel-nuc)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[16:14:20] INFO: Setting mode to netserver...
[16:14:20] INFO: Connected USB devices:
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 8087:0aaa Intel Corp. 
Bus 001 Device 011: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 001 Device 010: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 002: ID 0451:16a8 Texas Instruments, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[16:14:20] INFO: Generating /etc/nut/upsd.users...
[16:14:20] INFO: Configuring user: xxxx
[16:14:21] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[16:14:21] INFO: Configuring Device named APC1400...
[16:14:21] INFO: Starting the UPS drivers...
Using subdriver: APC HID 0.96
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:14:21] INFO: Starting the UPS information server...
   0.000000	fopen /var/run/nut/upsd.pid: No such file or directory
   0.000809	listening on 0.0.0.0 port 3493
   0.001886	Connected to UPS [APC1400]: usbhid-ups-APC1400
[16:14:21] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /var/run/nut/upsmon.pid: No such file or directory
   0.000240	Using power down flag file /etc/killpower
   0.000382	UPS: APC1400@localhost (master) (power value 1)
   0.000430	debug level is '1'
   0.000455	Warning: running as one big root process by request (upsmon -p)
   0.000682	Init SSL without certificate database
   0.002457	Trying to connect to UPS [APC1400@localhost]
   0.011828	User upsmonmaster@127.0.0.1 logged into UPS [APC1400]
   0.003767	Logged into UPS APC1400@localhost

Config configuration.yaml:
sensor:
 - platform: nut
  name: APC1400
  host: a0d7b954-nut
  port: 3493
  username: xxx
  password: xxxxx
  resources:
    - battery.runtime
    - ups.load
    - ups.status
    - input.voltage
    - ups.temperature
    - input.frequency
    - output.voltage
    - battery.voltage
 
Thanks
    - battery.charge

**Comment by sinclairpaul** [comment]
Configuration in Home Assistant has switched to the GUI, please configure it that way.  The addon has started and is running, therefore the issue is likely in the Integration.
