### ISSUE TITLE
SNMP driver devices provide insufficient details after latest version updates

### ISSUE THREAD

**Issue by kyletpugh** [hassio-addons/addon-nut#96]
# Problem/Motivation

> One of my UPS no longer reports the same information as before updating. I believe that upgrading to the latest release has caused an issue with SNMP devices again. I have two CyberPower CP1500PFCLCDa, one is connected to the server machine via a USB cable, the other is connected through the network and SNMP. For about a month both UPS devices were providing information, however, one of these past few updates has returned the SNMP driver device to minimal information. The log says that the CyberPower .mib is version 0.1 again. I cannot get the previous addon version to work anymore.

## Expected behavior

> I expect that both UPS report all information correctly.

## Actual behavior

> The SNMP driver device does not do anything but report runtime.

## Steps to reproduce

> Have a CyberPower SNMP device that uses RMCARD205. Probably other SNMP devices that require updated .mib because they were released after 2016.

## Proposed changes

> I believe NUT was being built from source before but now the packages are being installed. The packages have not been updated since 2016. The git repository is significantly ahead of the available packages.

**Comment by sinclairpaul** [comment]
We are now installing the Debian packages, previously we were building from the last release.

I wouldn't see there are any differences, however I would guess if there is a feature missing it should be logged against the Debian repo....

**Comment by kyletpugh** [comment]
I was changing the Dockerfile to download the repository source. I cannot get this to work anymore.

**Comment by sinclairpaul** [comment]
Then you would need to fork and run your own version, unfortunately that would be out of scope for this addon.  You can look at previous revisions if you need.

**Comment by kyletpugh** [comment]
I am asking for you to update to current hardware support, having support from 2016 is pretty useless... You're right though. I should have to fork this project and do what you should have already done.

**Comment by sinclairpaul** [comment]
I'm sorry, we run the release versions, if you would like something else the source is available.

Thanks for the input.
