### ISSUE TITLE
I'm sorry, we run the release versions, if you would like something else the source is available.

### ISSUE THREAD

**Issue by kyletpugh** [hassio-addons/addon-nut#97]
I'm sorry, we run the release versions, if you would like something else the source is available.

Thanks for the input.

_Originally posted by @sinclairpaul in https://github.com/hassio-addons/addon-nut/issues/96#issuecomment-778544999_

This was possible to just change before because it was being built. I did not have an issue, the packages are now being used and I cannot get it to work anymore. Why are you being a jerk? I'm trying to get my stuff to work. I'm not asking you to do it for me.

**Comment by kyletpugh** [comment]
And just to clarify, I am just asking for help figuring out why I can no longer build the source. I am trying to figure out what else broke my changes but you are unwilling to even help me figure out what I would need. I figured there could just be a way to add an option to use the repository instead for newer hardware support. Does there need to be another entire repository?

**Comment by frenck** [comment]
Running mainstream has pro and cons. Pro is stability, wider use and fixes, and lower maintenance needs. Running custom version bring newer, cutting edge feature, but add time to maintenance.

This is not just in keeping it work or updated, but also in terms of troubleshooting.


With more than 60 repos to maintain, we choose what is best for the larger audience, in such a way everything can be maintained.

This means that we won't support every use case. Feel free to write an maintain your own.

**Comment by kyletpugh** [comment]
I do not care about whatever you are talking about. I am trying to get my UPS working again. I have just built and installed NUT into my system without the add-on. I can not get the integration to work anymore, and the only thing was that I update this add-on. So I am trying to figure out what happened.

**Comment by frenck** [comment]
> I do not care about whatever you are talking about. 

Then we don't care either. 👋
